
***********************
* PGenCblE
***********************

   PARAMETERS AV8Emprcod , AV59Fecha , AV58Hora , AV57Usuari , AV40Ejenro , AV60Fchdde , AV61Fchhta
   * Program generated by GeneXus Version 8_0_3-109
   * Description: Generacion de Asientos Entrega
   *       Xbase: FOXPRO
   *  Index Type: CDX
   *   Interface: WINDOWS
   *             Client/Server related information
   *         API: odbc
   *      Driver: qesqlserver
   *      Server: dagridb
   *   Data Base: Dagri

   #INCLUDE gxdatain.prg
   IF TYPE("GXToReadEvents") = "U"
      PUBLIC GXToReadEvents
   ENDIF
   GXToReadEvents = .T.
   LOCAL GXReadEvObj
   IF TYPE("GXReadEvents") = "U"
      PRIVATE GXReadEvents
      GXReadEvObj = .T.
   ELSE
      GXReadEvObj = GXReadEvents
   ENDIF
   GXReadEvents = .F.
   IF GXReadEvObj
   ENDIF
   PRIVATE gxHDC, GX_XPage, GX_YPage, GXPrn_Flag
   gxHDC = 0
   GX_XPage = 96
   GX_YPage = 96
   GXPrn_Flag = 0
   ON KEY LABEL ENTER
   IF ! GXReadEvObj
      SET SAFETY OFF
      SET BELL OFF
      SET REPROCESS TO 1
      IF SET("DATE") != "BRITISH"
         SET DATE BRITISH
      ENDIF
      SET EXACT ON
      SET CONFIRM ON
      DO GX_YrLmt WITH 19, 40
      IF SET("HOURS") != 24
         SET HOURS TO 24
      ENDIF
      SET READBORDER OFF
      IF SET("POINT") != "."
         SET POINT TO "."
         SET SEPARATOR TO ","
      ENDIF
      DO GX_DSSet
   ENDIF

   PRIVATE Buf_P03148_986TesLin
   Buf_P03148_986TesLin = 0
   PRIVATE Buf_P03148_996TesImp
   Buf_P03148_996TesImp = 0.00
   PRIVATE Buf_P03148_1010TesCotImp
   Buf_P03148_1010TesCotImp = 0.0000
   PRIVATE Buf_P03148_1007TesMonCod
   Buf_P03148_1007TesMonCod = 0
   PRIVATE Buf_P03148_989TesMedCod
   Buf_P03148_989TesMedCod = 0
   PRIVATE Buf_P03148_987TesIoE
   Buf_P03148_987TesIoE = SPACE(1)
   PRIVATE Buf_P03148_985TesNroI
   Buf_P03148_985TesNroI = 0
   PRIVATE Buf_P03148_2EmpCod
   Buf_P03148_2EmpCod = 0
   PRIVATE HStmt_P03148
   HStmt_P03148 = -1
   PRIVATE Buf_P03147_124ChqCta
   Buf_P03147_124ChqCta = 0
   PRIVATE Buf_P03147_123ChqTip
   Buf_P03147_123ChqTip = SPACE(1)
   PRIVATE Buf_P03147_122ChqLin
   Buf_P03147_122ChqLin = 0
   PRIVATE Buf_P03147_131ChqImp
   Buf_P03147_131ChqImp = 0.00
   PRIVATE Buf_P03147_149ChqCotImp
   Buf_P03147_149ChqCotImp = 0.0000
   PRIVATE Buf_P03147_146ChqMonCod
   Buf_P03147_146ChqMonCod = 0
   PRIVATE Buf_P03147_121ChqNroI
   Buf_P03147_121ChqNroI = 0
   PRIVATE Buf_P03147_2EmpCod
   Buf_P03147_2EmpCod = 0
   PRIVATE HStmt_P03147
   HStmt_P03147 = -1
   PRIVATE Buf_P03146_1100EchCtaImp
   Buf_P03146_1100EchCtaImp = 0.00
   PRIVATE Buf_P03146_1091EchCtaCod
   Buf_P03146_1091EchCtaCod = SPACE(12)
   PRIVATE Buf_P03146_1083ECHNroInt
   Buf_P03146_1083ECHNroInt = 0
   PRIVATE Buf_P03146_2EmpCod
   Buf_P03146_2EmpCod = 0
   PRIVATE HStmt_P03146
   HStmt_P03146 = -1
   PRIVATE Buf_P03145_630McoEmpCta
   Buf_P03145_630McoEmpCta = SPACE(12)
   PRIVATE Buf_P03145_1377McoMonCod
   Buf_P03145_1377McoMonCod = 0
   PRIVATE Buf_P03145_629McoEmpCod
   Buf_P03145_629McoEmpCod = 0
   PRIVATE Buf_P03145_619MCoCod
   Buf_P03145_619MCoCod = 0
   PRIVATE HStmt_P03145
   HStmt_P03145 = -1
   PRIVATE HStmt_P03144
   HStmt_P03144 = -1
   PRIVATE HStmt_P03143
   HStmt_P03143 = -1
   PRIVATE Buf_P03142_1086EchMotDsc
   Buf_P03142_1086EchMotDsc = SPACE(30)
   PRIVATE Buf_P03142_1084ECHNro
   Buf_P03142_1084ECHNro = 0
   PRIVATE Buf_P03142_1265EchEst
   Buf_P03142_1265EchEst = 0
   PRIVATE Buf_P03142_1085ECHMotCod
   Buf_P03142_1085ECHMotCod = 0
   PRIVATE Buf_P03142_2EmpCod
   Buf_P03142_2EmpCod = 0
   PRIVATE Buf_P03142_1139ECHFch
   Buf_P03142_1139ECHFch = CTOD("  /  /  ")
   PRIVATE Buf_P03142_1083ECHNroInt
   Buf_P03142_1083ECHNroInt = 0
   PRIVATE HStmt_P03142
   HStmt_P03142 = -1

   PRIVATE UserCancel, GX_newwin, GX_eject, GX_prn_defa, GX_env_def, GX_retp
   UserCancel = .F.
   GX_newwin = "GXDummyWin"
   GX_eject = .T.
   GX_XProp = 1
   gx_prn_defa = ""
   gx_env_def = .f.
   GX_retp = 0
   PRIVATE gx_oldDVal
   gx_oldDVal = CTOD("  /  /  ")

   PRIVATE currSoapErr, currSoapErrmsg
   currSoapErr = 0
   currSoapErrmsg = ""
   PRIVATE GX_pg_started
   GX_pg_started = .F.
   * Variables Definition
   PRIVATE AV8Emprcod
   PRIVATE AV59Fecha
   PRIVATE AV58Hora
   PRIVATE AV57Usuari
   PRIVATE AV40Ejenro
   PRIVATE AV60Fchdde
   PRIVATE AV61Fchhta
   PRIVATE Gx_out
   Gx_out = 'SCR'
   PRIVATE R1284TesNr
   R1284TesNr = SPACE(10)
   PRIVATE R1268TesFc
   R1268TesFc = CTOD("  /  /  ")
   PRIVATE R1006TesCt
   R1006TesCt = 0
   PRIVATE R1005TesES
   R1005TesES = 0
   PRIVATE R1003TesEn
   R1003TesEn = 0
   PRIVATE R1002TesEn
   R1002TesEn = SPACE(2)
   PRIVATE R1001TesNr
   R1001TesNr = 0
   PRIVATE R1000TesSu
   R1000TesSu = 0
   PRIVATE R999TesSer
   R999TesSer = SPACE(1)
   PRIVATE R998TesTip
   R998TesTip = SPACE(4)
   PRIVATE R997TesFch
   R997TesFch = CTOD("  /  /  ")
   PRIVATE R995TesNro
   R995TesNro = 0
   PRIVATE R994TesNro
   R994TesNro = 0
   PRIVATE R993TesBco
   R993TesBco = 0
   PRIVATE R991TesBco
   R991TesBco = 0
   PRIVATE R988TesFch
   R988TesFch = CTOD("  /  /  ")
   PRIVATE R986TesLin
   R986TesLin = 0
   PRIVATE R3038ChqRE
   R3038ChqRE = CTOD("  /  /  ")
   PRIVATE R3037ChqRE
   R3037ChqRE = 0
   PRIVATE R3036ChrRE
   R3036ChrRE = SPACE(2)
   PRIVATE R3035ChqRE
   R3035ChqRE = CTOD("  /  /  ")
   PRIVATE R2806ChqEs
   R2806ChqEs = 0
   PRIVATE R2008chqus
   R2008chqus = SPACE(10)
   PRIVATE R2007chqre
   R2007chqre = 0
   PRIVATE R2006chqfc
   R2006chqfc = CTOT("  /  /  ")
   PRIVATE R1994AuxCo
   R1994AuxCo = 0
   PRIVATE R1816ChqOr
   R1816ChqOr = SPACE(50)
   PRIVATE R1733ChqIm
   R1733ChqIm = 0
   PRIVATE R1663ChqCr
   R1663ChqCr = SPACE(1)
   PRIVATE R1651ChqCP
   R1651ChqCP = SPACE(8)
   PRIVATE R1269ChqFc
   R1269ChqFc = CTOD("  /  /  ")
   PRIVATE R145ChqNoO
   R145ChqNoO = SPACE(1)
   PRIVATE R144ChqBco
   R144ChqBco = 0
   PRIVATE R142ChqBco
   R142ChqBco = 0
   PRIVATE R141ChqFch
   R141ChqFch = CTOD("  /  /  ")
   PRIVATE R139ChqPrv
   R139ChqPrv = 0
   PRIVATE R138ChqPrv
   R138ChqPrv = SPACE(2)
   PRIVATE R137ChqNro
   R137ChqNro = 0
   PRIVATE R136ChqEst
   R136ChqEst = 0
   PRIVATE R134ChqCli
   R134ChqCli = 0
   PRIVATE R133ChqCli
   R133ChqCli = SPACE(2)
   PRIVATE R132ChqFch
   R132ChqFch = CTOD("  /  /  ")
   PRIVATE R130ChqTit
   R130ChqTit = SPACE(40)
   PRIVATE R129ChqNro
   R129ChqNro = SPACE(10)
   PRIVATE R128ChqSuc
   R128ChqSuc = 0
   PRIVATE R126ChqBco
   R126ChqBco = 0
   PRIVATE R125ChqFch
   R125ChqFch = CTOD("  /  /  ")
   PRIVATE R124ChqCta
   R124ChqCta = 0
   PRIVATE R123ChqTip
   R123ChqTip = SPACE(1)
   PRIVATE R122ChqLin
   R122ChqLin = 0
   PRIVATE R3628EchNr
   R3628EchNr = 0
   PRIVATE R3542EchND
   R3542EchND = SPACE(30)
   PRIVATE R3541EchDc
   R3541EchDc = 0
   PRIVATE R1088EchPC
   R1088EchPC = 0
   PRIVATE R561TraCod
   R561TraCod = 0
   PRIVATE R3067EchEm
   R3067EchEm = 0
   PRIVATE R1457EchFc
   R1457EchFc = CTOD("  /  /  ")
   PRIVATE R1271EchFc
   R1271EchFc = CTOD("  /  /  ")
   PRIVATE R1124EchUL
   R1124EchUL = 0
   PRIVATE R1087EchOb
   R1087EchOb = SPACE(40)
   PRIVATE R1392TAGAs
   R1392TAGAs = CTOD("  /  /  ")
   PRIVATE R985TesNro
   R985TesNro = 0
   PRIVATE R987TesIoE
   R987TesIoE = SPACE(1)
   PRIVATE R989TesMed
   R989TesMed = 0
   PRIVATE R1007TesMo
   R1007TesMo = 0
   PRIVATE R1010TesCo
   R1010TesCo = 0.0000
   PRIVATE R996TesImp
   R996TesImp = 0.00
   PRIVATE R121ChqNro
   R121ChqNro = 0
   PRIVATE R146ChqMon
   R146ChqMon = 0
   PRIVATE R149ChqCot
   R149ChqCot = 0.0000
   PRIVATE R131ChqImp
   R131ChqImp = 0.00
   PRIVATE R1091EchCt
   R1091EchCt = SPACE(12)
   PRIVATE R1100EchCt
   R1100EchCt = 0.00
   PRIVATE R619MCoCod
   R619MCoCod = 0
   PRIVATE R629McoEmp
   R629McoEmp = 0
   PRIVATE R1377McoMo
   R1377McoMo = 0
   PRIVATE R630McoEmp
   R630McoEmp = SPACE(12)
   PRIVATE RV71GXLvl1
   RV71GXLvl1 = 0
   PRIVATE R1393TAGAs
   R1393TAGAs = SPACE(40)
   PRIVATE R1384TAGAs
   R1384TAGAs = 0
   PRIVATE R1385TAGAs
   R1385TAGAs = SPACE(12)
   PRIVATE R1386TAGAs
   R1386TAGAs = 0.00
   PRIVATE R1387TAGAs
   R1387TAGAs = 0.00
   PRIVATE R1713TAGAS
   R1713TAGAS = 0
   PRIVATE R1085ECHMo
   R1085ECHMo = 0
   PRIVATE R1265EchEs
   R1265EchEs = 0
   PRIVATE R1084ECHNr
   R1084ECHNr = 0
   PRIVATE R1086EchMo
   R1086EchMo = SPACE(30)
   PRIVATE R2EmpCod
   R2EmpCod = 0
   PRIVATE R1380TAGNi
   R1380TAGNi = 0
   PRIVATE R1381TAGAs
   R1381TAGAs = 0
   PRIVATE R1083ECHNr
   R1083ECHNr = 0
   PRIVATE R1382TAGAs
   R1382TAGAs = 0
   PRIVATE R1139ECHFc
   R1139ECHFc = CTOD("  /  /  ")
   PRIVATE R1390TAGAs
   R1390TAGAs = CTOD("  /  /  ")
   PRIVATE R1391TAGAs
   R1391TAGAs = SPACE(40)
   PRIVATE R1383TAGAs
   R1383TAGAs = 0
   PRIVATE Gx_emsg
   Gx_emsg = SPACE(70)
   PRIVATE Gx_err
   Gx_err = 0
   PRIVATE RV67Tesioe
   RV67Tesioe = SPACE(1)
   PRIVATE RV66Signo
   RV66Signo = 0
   PRIVATE RV65Echnro
   RV65Echnro = 0
   PRIVATE RV64Tesmed
   RV64Tesmed = 0
   PRIVATE RV63Tescot
   RV63Tescot = 0.0000
   PRIVATE RV62Tesmon
   RV62Tesmon = 0
   PRIVATE RV56Graba
   RV56Graba = SPACE(1)
   PRIVATE RV55Asiitd
   RV55Asiitd = SPACE(40)
   PRIVATE RV54Asinro
   RV54Asinro = 0
   PRIVATE RV53Haber
   RV53Haber = 0.00
   PRIVATE RV52Debe
   RV52Debe = 0.00
   PRIVATE RV51Total
   RV51Total = 0.00
   PRIVATE RV50Nroit
   RV50Nroit = 0
   PRIVATE RV49Imporr[100]
   DIMENSION RV49Imporr[100]
   RV49Imporr = 0.00
   PRIVATE RV48Cuenta[100]
   DIMENSION RV48Cuenta[100]
   RV48Cuenta = SPACE(12)
   PRIVATE RV47Rettip
   RV47Rettip = SPACE(6)
   PRIVATE RV46Nvo
   RV46Nvo = SPACE(1)
   PRIVATE RV45Ctanro
   RV45Ctanro = SPACE(12)
   PRIVATE RV44Cuenta[100]
   DIMENSION RV44Cuenta[100]
   RV44Cuenta = SPACE(12)
   PRIVATE RV43Deudor
   RV43Deudor = 0.00
   PRIVATE RV42Ni
   RV42Ni = 0
   PRIVATE RV41Ctadeu
   RV41Ctadeu = SPACE(12)
   PRIVATE RV39Nihta
   RV39Nihta = 0
   PRIVATE RV38Nidde
   RV38Nidde = 0
   PRIVATE RV36J
   RV36J = 0
   PRIVATE RV35Mes[12]
   DIMENSION RV35Mes[12]
   RV35Mes = SPACE(5)
   PRIVATE RV33Top
   RV33Top = SPACE(1)
   PRIVATE RV32I
   RV32I = 0
   PRIVATE RV30Import[100]
   DIMENSION RV30Import[100]
   RV30Import = 0.00
   PRIVATE RV29Entraz
   RV29Entraz = SPACE(20)
   PRIVATE RV28Tipo
   RV28Tipo = SPACE(4)
   PRIVATE RV27Titulo
   RV27Titulo = SPACE(80)
   PRIVATE RV26Compra
   RV26Compra = SPACE(1)
   PRIVATE RV25Impimp
   RV25Impimp = SPACE(1)
   PRIVATE RV23Hasnro
   RV23Hasnro = 0
   PRIVATE RV22Hasfch
   RV22Hasfch = CTOD("  /  /  ")
   PRIVATE RV20Estado
   RV20Estado = 0
   PRIVATE RV18Desraz
   RV18Desraz = SPACE(40)
   PRIVATE RV17Hasnro
   RV17Hasnro = 0
   PRIVATE RV16Desnro
   RV16Desnro = 0
   PRIVATE RV15Hasfch
   RV15Hasfch = CTOD("  /  /  ")
   PRIVATE RV14Desfch
   RV14Desfch = CTOD("  /  /  ")
   PRIVATE RV12Despro
   RV12Despro = 0
   PRIVATE RV11Lei
   RV11Lei = 0
   PRIVATE RV10Emprno
   RV10Emprno = SPACE(30)
   PRIVATE RV9Fechasi
   RV9Fechasi = CTOD("  /  /  ")
   * Level Flags
   PRIVATE LEVEL3
   LEVEL3 = .F.
   PRIVATE LEVEL2
   LEVEL2 = .F.
   PRIVATE LEVEL4
   LEVEL4 = .F.
   PRIVATE LEVEL5
   LEVEL5 = .F.
   PRIVATE LEVEL6
   LEVEL6 = .F.
   PRIVATE LEVEL7
   LEVEL7 = .F.
   PRIVATE LEVEL8
   LEVEL8 = .F.
   PRIVATE LEVEL1
   LEVEL1 = .F.
   * Cursors Definition
   PRIVATE GX_OP108
   GX_OP108 = .F.
   PRIVATE GX_REC108
   GX_REC108 = 0
   PRIVATE GX_OP14
   GX_OP14 = .F.
   PRIVATE GX_REC14
   GX_REC14 = 0
   PRIVATE GX_OP379
   GX_OP379 = .F.
   PRIVATE GX_REC379
   GX_REC379 = 0
   PRIVATE GX_OP162
   GX_OP162 = .F.
   PRIVATE GX_REC162
   GX_REC162 = 0
   PRIVATE GX_OP159
   GX_OP159 = .F.
   PRIVATE GX_REC159
   GX_REC159 = 0
   PRIVATE GX_OP119
   GX_OP119 = .F.
   PRIVATE GX_REC119
   GX_REC119 = 0
   PRIVATE GX_OP158
   GX_OP158 = .F.
   PRIVATE GX_REC158
   GX_REC158 = 0
   * Gx formulas
   Gx_err = 0
   * Device settings
   PRIVATE old_area, rpt_name, RptView
   old_area = 0
   rpt_name = " "
   RptView = .F.
   LEVEL1 = .T.
   DO RLeeEmp WITH AV8Emprcod , RV10Emprno
   RV38Nidde = 0
   RV39Nihta = 0
   DO PSkNrI WITH AV8Emprcod , RV42Ni
   RV38Nidde = RV42Ni
   RV39Nihta = RV42Ni
   RV44Cuenta = "0000.00000"
   RV30Import = 0
   RV41Ctadeu = "1110.25000"
   LEVEL2 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03142" , @HStmt_P03142 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03142","",GX_CURSOR_TYPE_READONLY,@HStmt_P03142) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [ECHNroInt], [ECHFch], [EmpCod], [ECHMotCod], [EchEst], [ECHNro], [EchMotDsc] "
      cmdbuf = cmdbuf + "  FROM [ENTCHE] (NOLOCK) WHERE ([EmpCod] = ? and [ECHFch] >= ?) AND ([ECHMotCod] > "
      cmdbuf = cmdbuf + "  0) AND ([EchEst] < 9) AND ([ECHFch] <= ?) ORDER BY [EmpCod], [ECHFch]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03142,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_P03142,100)
      GX_DB_BindColsP03142_01 ()
      GX_DB_BindParmP03142_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_P03142,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetDate( HStmt_P03142,2,@AV60Fchdde,0)
   Gx_err = GX_DB_SetDate( HStmt_P03142,3,@AV61Fchhta,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_P03142) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   P03142 = Gx_err
   GX_DB_GetP03142_01 ()
   DO WHILE P03142 <> 101
      R1083ECHNr = Buf_P03142_1083ECHNroInt
      R1139ECHFc = Buf_P03142_1139ECHFch
      R2EmpCod = Buf_P03142_2EmpCod
      R1085ECHMo = Buf_P03142_1085ECHMotCod
      R1265EchEs = Buf_P03142_1265EchEst
      R1084ECHNr = Buf_P03142_1084ECHNro
      R1086EchMo = Buf_P03142_1086EchMotDsc
      RV54Asinro = R1083ECHNr
      RV55Asiitd = R1086EchMo + "(" + str( R1084ECHNr , 8 ) + ")"
      LEVEL3 = .T.
      * INSERT RECORD ON TABLE TASIGES
      GX_INS158 = 0
      R1380TAGNi = RV42Ni
      R1381TAGAs = 5
      R1382TAGAs = R1083ECHNr
      R1390TAGAs = GXFEOMVF( R1139ECHFc )
      R1391TAGAs = "Entr/Ingr Mes " + str( month( R1139ECHFc ) , 2 )
      R1383TAGAs = 0
      RV50Nroit = 1
      DO GX_CSC01
      IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03143" , @HStmt_P03143 )
         Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03143","",GX_CURSOR_TYPE_FORUPDATE,@HStmt_P03143) ,  ,  ,  , CS_SQLSRV ,  )
         cmdbuf = " INSERT INTO [TASIGES] ([EmpCod], [TAGNi], [TAGAsiTip], [TAGAsiNI], [TAGAsiUNro], "
         cmdbuf = cmdbuf + "  [TAGAsiFch], [TAGAsiDsc]) VALUES (?, ?, ?, ?, ?, ?, ?) "
         Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03143,cmdbuf)
         GX_DB_BindParmP03143_01 ()
      ENDIF
      Gx_err = GX_DB_SetInt( HStmt_P03143,1,@R2EmpCod,0)
      Gx_err = GX_DB_SetDouble( HStmt_P03143,2,@R1380TAGNi,0)
      Gx_err = GX_DB_SetInt( HStmt_P03143,3,@R1381TAGAs,0)
      Gx_err = GX_DB_SetDouble( HStmt_P03143,4,@R1382TAGAs,0)
      Gx_err = GX_DB_SetLong( HStmt_P03143,5,@R1383TAGAs,0)
      Gx_err = GX_DB_SetDate( HStmt_P03143,6,@R1390TAGAs,0)
      Gx_err = GX_DB_SetStr( HStmt_P03143,7,R1391TAGAs,40,0)
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtExecute( HStmt_P03143) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      P03143 = Gx_err
      Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03143) ,  ,  ,  , CS_SQLSRV ,  )
      IF P03143 = 1
         Gx_err = 1
         Gx_emsg = "Ya existe el registro"
      ELSE
         Gx_err = 0
         Gx_emsg = ""
      ENDIF
      * End Insert
      LEVEL3 = .F.
      RV44Cuenta = "0000.00000"
      RV30Import = 0
      RV65Echnro = R1083ECHNr
      IF R1085ECHMo < 999
         RV66Signo = -1
         GX_retp = 0
         DO U118Q2
         IF GX_retp = 1
            RETURN
         ENDIF
         RV67Tesioe = "E"
         GX_retp = 0
         DO U128Q2
         IF GX_retp = 1
            RETURN
         ENDIF
         RV32I = 0
         RV50Nroit = 1
         RV51Total = 0
         DO WHILE RV32I < 100 .AND. RV44Cuenta[RV32I+1] <> "0000.00000"
            RV32I = RV32I + 1
            IF RV44Cuenta[RV32I] <> "0000.00000" .AND. RV30Import[RV32I] <> 0
               RV45Ctanro = RV44Cuenta[RV32I]
               IF RV30Import[RV32I] > 0
                  RV52Debe = 0
                  RV53Haber = RV30Import[RV32I]
               ELSE
                  RV52Debe = - RV30Import[RV32I]
                  RV53Haber = 0
               ENDIF
               RV54Asinro = R1083ECHNr
               GX_retp = 0
               DO U138Q2
               IF GX_retp = 1
                  RETURN
               ENDIF
               RV50Nroit = RV50Nroit + 1
            ENDIF
            IF UserCancel
               EXIT
            ENDIF
         ENDDO
      ELSE
         RV66Signo = -1
         GX_retp = 0
         DO U118Q2
         IF GX_retp = 1
            RETURN
         ENDIF
         GX_retp = 0
         DO U148Q2
         IF GX_retp = 1
            RETURN
         ENDIF
         RV67Tesioe = "I"
         GX_retp = 0
         DO U128Q2
         IF GX_retp = 1
            RETURN
         ENDIF
         RV32I = 0
         RV50Nroit = 1
         RV51Total = 0
         DO WHILE RV32I < 100 .AND. RV44Cuenta[RV32I+1] <> "0000.00000"
            RV32I = RV32I + 1
            IF RV44Cuenta[RV32I] <> "0000.00000" .AND. RV30Import[RV32I] <> 0
               RV45Ctanro = RV44Cuenta[RV32I]
               IF RV30Import[RV32I] > 0
                  RV52Debe = RV30Import[RV32I]
                  RV53Haber = 0
               ELSE
                  RV52Debe = 0
                  RV53Haber = - RV30Import[RV32I]
               ENDIF
               RV54Asinro = R1083ECHNr
               GX_retp = 0
               DO U138Q2
               IF GX_retp = 1
                  RETURN
               ENDIF
               RV50Nroit = RV50Nroit + 1
            ENDIF
            IF UserCancel
               EXIT
            ENDIF
         ENDDO
      ENDIF
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_P03142) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      P03142 = Gx_err
      GX_DB_GetP03142_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03142) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL2 = .F.
   RV56Graba = "N"
   DO WGenCbl WITH AV8Emprcod , RV38Nidde , RV39Nihta , RV56Graba , AV40Ejenro
   IF RV56Graba = "S"
      DO PGenCbl WITH AV8Emprcod , RV38Nidde , RV39Nihta , AV57Usuari , AV40Ejenro , 5 , AV57Usuari , AV59Fecha , AV58Hora
   ENDIF
   DO EP8Q0
   RETURN
   DO EP8Q0
   RETURN
   GX_retp = 0
* End Program

***********************
PROCEDURE EP8Q0
***********************

   IF TYPE( "HConn_Default" ) = "N"
      IF GXCONNECTED
         Gx_Err = Gx_odbc_mrc( GX_DB_ConnCommit(HConn_Default) ,  ,  ,  , CS_SQLSRV ,  )
      ENDIF
   ENDIF
   DO CD8Q0
   IF WEXIST( GX_newwin )
      RELEASE WINDOW (GX_newwin)
      IF !EMPTY( LastWin )
         ACTIVATE WINDOW (LastWin)
         MODIFY WINDOW (LastWin) CLOSE
      ENDIF
   ENDIF
RETURN

***********************
PROCEDURE U138Q2
***********************

   * 'ALTAITEM' Routine
   LEVEL4 = .T.
   * INSERT RECORD ON TABLE TASIGES1
   GX_INS159 = 0
   R2EmpCod = AV8Emprcod
   R1380TAGNi = RV42Ni
   R1381TAGAs = 5
   R1393TAGAs = RV55Asiitd
   R1382TAGAs = RV54Asinro
   R1384TAGAs = RV50Nroit
   RV50Nroit = RV50Nroit + 1
   R1385TAGAs = RV45Ctanro
   R1386TAGAs = RV52Debe
   R1387TAGAs = RV53Haber
   IF RV53Haber > RV52Debe
      R1713TAGAS = 2
   ELSE
      R1713TAGAS = 1
   ENDIF
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03144" , @HStmt_P03144 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03144","",GX_CURSOR_TYPE_FORUPDATE,@HStmt_P03144) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " INSERT INTO [TASIGES1] ([EmpCod], [TAGNi], [TAGAsiTip], [TAGAsiNI], [TAGAsiItNr], "
      cmdbuf = cmdbuf + "  [TAGAsiCTaN], [TAGAsiDebe], [TAGAsiHabe], [TAGAsiItDs], [TAGASIdOh], [TAGAsiItFc]) "
      cmdbuf = cmdbuf + "  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, convert( DATETIME, '17530101', 112 )) "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03144,cmdbuf)
      GX_DB_BindParmP03144_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_P03144,1,@R2EmpCod,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03144,2,@R1380TAGNi,0)
   Gx_err = GX_DB_SetInt( HStmt_P03144,3,@R1381TAGAs,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03144,4,@R1382TAGAs,0)
   Gx_err = GX_DB_SetLong( HStmt_P03144,5,@R1384TAGAs,0)
   Gx_err = GX_DB_SetStr( HStmt_P03144,6,R1385TAGAs,12,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03144,7,@R1386TAGAs,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03144,8,@R1387TAGAs,0)
   Gx_err = GX_DB_SetStr( HStmt_P03144,9,R1393TAGAs,40,0)
   Gx_err = GX_DB_SetInt( HStmt_P03144,10,@R1713TAGAS,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtExecute( HStmt_P03144) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   P03144 = Gx_err
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03144) ,  ,  ,  , CS_SQLSRV ,  )
   IF P03144 = 1
      Gx_err = 1
      Gx_emsg = "Ya existe el registro"
   ELSE
      Gx_err = 0
      Gx_emsg = ""
   ENDIF
   * End Insert
   LEVEL4 = .F.
RETURN

***********************
PROCEDURE U158Q1
***********************

   * 'CUENTA' Routine
   RV71GXLvl1 = 0
   LEVEL5 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03145" , @HStmt_P03145 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03145","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_P03145) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [MCoCod], [McoEmpCod], [McoMonCod], [McoEmpCta] FROM [MEDCOB1] (NOLOCK) WHERE "
      cmdbuf = cmdbuf + "  [MCoCod] = ? and [McoEmpCod] = ? and [McoMonCod] = ? ORDER BY [MCoCod], [McoEmpCod], "
      cmdbuf = cmdbuf + "  [McoMonCod]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03145,cmdbuf)
      GX_DB_BindColsP03145_01 ()
      GX_DB_BindParmP03145_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_P03145,1,@RV64Tesmed,0)
   Gx_err = GX_DB_SetInt( HStmt_P03145,2,@AV8Emprcod,0)
   Gx_err = GX_DB_SetInt( HStmt_P03145,3,@RV62Tesmon,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_P03145) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   P03145 = Gx_err
   GX_DB_GetP03145_01 ()
   DO WHILE P03145 <> 101
      R619MCoCod = Buf_P03145_619MCoCod
      R629McoEmp = Buf_P03145_629McoEmpCod
      R1377McoMo = Buf_P03145_1377McoMonCod
      R630McoEmp = Buf_P03145_630McoEmpCta
      RV71GXLvl1 = 1
      RV45Ctanro = R630McoEmp
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      * Exiting from a For First loop.
      EXIT
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03145) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL5 = .F.
   IF RV71GXLvl1 = 0
      RV45Ctanro = "9898.9898"
   ENDIF
   RV32I = 0
   RV46Nvo = "S"
   DO WHILE RV32I < 100 .AND. RV46Nvo = "S"
      RV32I = RV32I + 1
      IF RV44Cuenta[RV32I] = RV45Ctanro
         RV46Nvo = "N"
         RV36J = RV32I
      ELSE
         IF RV44Cuenta[RV32I] = "0000.00000"
            RV36J = RV32I
            RV32I = 101
         ENDIF
      ENDIF
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   RV44Cuenta[RV36J] = RV45Ctanro
RETURN

***********************
PROCEDURE U118Q2
***********************

   * 'ENTCHE2' Routine
   LEVEL6 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03146" , @HStmt_P03146 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03146","",GX_CURSOR_TYPE_READONLY_NOTNESTED,@HStmt_P03146) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [EmpCod], [ECHNroInt], [EchCtaCod], [EchCtaImp] FROM [ENTCHE2] (NOLOCK) WHERE "
      cmdbuf = cmdbuf + "  [EmpCod] = ? and [ECHNroInt] = ? ORDER BY [EmpCod], [ECHNroInt], [EchCtaCod]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03146,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_P03146,100)
      GX_DB_BindColsP03146_01 ()
      GX_DB_BindParmP03146_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_P03146,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03146,2,@RV65Echnro,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_P03146) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   P03146 = Gx_err
   GX_DB_GetP03146_01 ()
   DO WHILE P03146 <> 101
      R2EmpCod = Buf_P03146_2EmpCod
      R1083ECHNr = Buf_P03146_1083ECHNroInt
      R1091EchCt = Buf_P03146_1091EchCtaCod
      R1100EchCt = Buf_P03146_1100EchCtaImp
      RV32I = 0
      RV36J = 101
      RV46Nvo = "S"
      DO WHILE RV32I < 100 .AND. RV46Nvo = "S"
         RV32I = RV32I + 1
         IF RV44Cuenta[RV32I] = R1091EchCt
            RV46Nvo = "N"
            RV36J = RV32I
         ELSE
            IF RV44Cuenta[RV32I] = "0000.00000"
               RV36J = RV32I
               RV32I = 101
            ENDIF
         ENDIF
         IF UserCancel
            EXIT
         ENDIF
      ENDDO
      RV44Cuenta[RV36J] = R1091EchCt
      RV30Import[RV36J] = RV30Import[RV36J] + R1100EchCt * RV66Signo
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_P03146) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      P03146 = Gx_err
      GX_DB_GetP03146_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03146) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL6 = .F.
RETURN

***********************
PROCEDURE U148Q2
***********************

   * 'ENTCHE3' Routine
   LEVEL7 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03147" , @HStmt_P03147 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03147","",GX_CURSOR_TYPE_READONLY,@HStmt_P03147) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [EmpCod], [ChqNroI], [ChqMonCod], [ChqCotImp], [ChqImp], [ChqLin], [ChqTip], "
      cmdbuf = cmdbuf + "  [ChqCta] FROM [CHQS] (NOLOCK) WHERE [EmpCod] = ? and [ChqNroI] = ? ORDER BY [EmpCod], "
      cmdbuf = cmdbuf + "  [ChqNroI], [ChqLin], [ChqTip], [ChqCta]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03147,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_P03147,100)
      GX_DB_BindColsP03147_01 ()
      GX_DB_BindParmP03147_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_P03147,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03147,2,@RV65Echnro,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_P03147) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   P03147 = Gx_err
   GX_DB_GetP03147_01 ()
   DO WHILE P03147 <> 101
      R2EmpCod = Buf_P03147_2EmpCod
      R121ChqNro = Buf_P03147_121ChqNroI
      R146ChqMon = Buf_P03147_146ChqMonCod
      R149ChqCot = Buf_P03147_149ChqCotImp
      R131ChqImp = Buf_P03147_131ChqImp
      R122ChqLin = Buf_P03147_122ChqLin
      R123ChqTip = Buf_P03147_123ChqTip
      R124ChqCta = Buf_P03147_124ChqCta
      RV64Tesmed = 3
      RV62Tesmon = R146ChqMon
      GX_retp = 0
      DO U158Q1
      IF GX_retp = 1
         RETURN
      ENDIF
      IF R149ChqCot = 0
         RV63Tescot = 1
      ELSE
         RV63Tescot = R149ChqCot
      ENDIF
      RV30Import[RV36J] = RV30Import[RV36J] - R131ChqImp * RV63Tescot * RV66Signo
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_P03147) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      P03147 = Gx_err
      GX_DB_GetP03147_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03147) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL7 = .F.
RETURN

***********************
PROCEDURE U128Q2
***********************

   * 'TESCYP' Routine
   LEVEL8 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "P03148" , @HStmt_P03148 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"PGENCBLE","P03148","",GX_CURSOR_TYPE_READONLY,@HStmt_P03148) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [EmpCod], [TesNroI], [TesIoE], [TesMedCod], [TesMonCod], [TesCotImp], [TesImp], "
      cmdbuf = cmdbuf + "  [TesLin] FROM [TESCYP] (NOLOCK) WHERE ([EmpCod] = ? and [TesNroI] = ?) AND ([TesIoE] "
      cmdbuf = cmdbuf + "  = ?) AND ([TesIoE] = 'E' or [TesMedCod] <> 3) ORDER BY [EmpCod], [TesNroI], [TesLin] "
      cmdbuf = cmdbuf + "   "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_P03148,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_P03148,100)
      GX_DB_BindColsP03148_01 ()
      GX_DB_BindParmP03148_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_P03148,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetDouble( HStmt_P03148,2,@RV65Echnro,0)
   Gx_err = GX_DB_SetStr( HStmt_P03148,3,RV67Tesioe,1,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_P03148) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   P03148 = Gx_err
   GX_DB_GetP03148_01 ()
   DO WHILE P03148 <> 101
      R2EmpCod = Buf_P03148_2EmpCod
      R985TesNro = Buf_P03148_985TesNroI
      R987TesIoE = Buf_P03148_987TesIoE
      R989TesMed = Buf_P03148_989TesMedCod
      R1007TesMo = Buf_P03148_1007TesMonCod
      R1010TesCo = Buf_P03148_1010TesCotImp
      R996TesImp = Buf_P03148_996TesImp
      R986TesLin = Buf_P03148_986TesLin
      RV64Tesmed = R989TesMed
      RV62Tesmon = R1007TesMo
      GX_retp = 0
      DO U158Q1
      IF GX_retp = 1
         RETURN
      ENDIF
      IF R1010TesCo = 0
         RV63Tescot = 1
      ELSE
         RV63Tescot = R1010TesCo
      ENDIF
      RV30Import[RV36J] = RV30Import[RV36J] + R996TesImp * RV63Tescot
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_P03148) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      P03148 = Gx_err
      GX_DB_GetP03148_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_P03148) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL8 = .F.
RETURN
PROCEDURE GX_DB_GetP03148_01
   Gx_err = GX_DB_GetColInt( HStmt_P03148,1,@Buf_P03148_2EmpCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03148,2,@Buf_P03148_985TesNroI,0)
   Gx_err = GX_DB_GetColStr( HStmt_P03148,3,@Buf_P03148_987TesIoE,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03148,4,@Buf_P03148_989TesMedCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03148,5,@Buf_P03148_1007TesMonCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03148,6,@Buf_P03148_1010TesCotImp,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03148,7,@Buf_P03148_996TesImp,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03148,8,@Buf_P03148_986TesLin,0)
ENDPROC

PROCEDURE GX_DB_GetP03147_01
   Gx_err = GX_DB_GetColInt( HStmt_P03147,1,@Buf_P03147_2EmpCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03147,2,@Buf_P03147_121ChqNroI,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03147,3,@Buf_P03147_146ChqMonCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03147,4,@Buf_P03147_149ChqCotImp,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03147,5,@Buf_P03147_131ChqImp,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03147,6,@Buf_P03147_122ChqLin,0)
   Gx_err = GX_DB_GetColStr( HStmt_P03147,7,@Buf_P03147_123ChqTip,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03147,8,@Buf_P03147_124ChqCta,0)
ENDPROC

PROCEDURE GX_DB_GetP03146_01
   Gx_err = GX_DB_GetColInt( HStmt_P03146,1,@Buf_P03146_2EmpCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03146,2,@Buf_P03146_1083ECHNroInt,0)
   Gx_err = GX_DB_GetColStr( HStmt_P03146,3,@Buf_P03146_1091EchCtaCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_P03146,4,@Buf_P03146_1100EchCtaImp,0)
ENDPROC

PROCEDURE GX_DB_GetP03145_01
   Gx_err = GX_DB_GetColInt( HStmt_P03145,1,@Buf_P03145_619MCoCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03145,2,@Buf_P03145_629McoEmpCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03145,3,@Buf_P03145_1377McoMonCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_P03145,4,@Buf_P03145_630McoEmpCta,0)
ENDPROC

PROCEDURE GX_DB_GetP03142_01
   Gx_err = GX_DB_GetColDouble( HStmt_P03142,1,@Buf_P03142_1083ECHNroInt,0)
   Gx_err = GX_DB_GetColDate( HStmt_P03142,2,@Buf_P03142_1139ECHFch,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03142,3,@Buf_P03142_2EmpCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03142,4,@Buf_P03142_1085ECHMotCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_P03142,5,@Buf_P03142_1265EchEst,0)
   Gx_err = GX_DB_GetColLong( HStmt_P03142,6,@Buf_P03142_1084ECHNro,0)
   Gx_err = GX_DB_GetColStr( HStmt_P03142,7,@Buf_P03142_1086EchMotDsc,0)
ENDPROC

PROCEDURE GX_DB_BindColsP03148_01
   Gx_err = GX_DB_BindColShort( HStmt_P03148,1,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03148,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_P03148,3,0,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03148,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03148,5,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03148,6,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03148,7,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03148,8,0)
ENDPROC
PROCEDURE GX_DB_BindColsP03147_01
   Gx_err = GX_DB_BindColShort( HStmt_P03147,1,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03147,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03147,3,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03147,4,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03147,5,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03147,6,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_P03147,7,0,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03147,8,0)
ENDPROC
PROCEDURE GX_DB_BindColsP03146_01
   Gx_err = GX_DB_BindColShort( HStmt_P03146,1,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03146,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_P03146,3,0,12,0)
   Gx_err = GX_DB_BindColDouble( HStmt_P03146,4,0)
ENDPROC
PROCEDURE GX_DB_BindColsP03145_01
   Gx_err = GX_DB_BindColShort( HStmt_P03145,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03145,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03145,3,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_P03145,4,0,12,0)
ENDPROC
PROCEDURE GX_DB_BindColsP03142_01
   Gx_err = GX_DB_BindColDouble( HStmt_P03142,1,0)
   Gx_err = GX_DB_BindColDate( HStmt_P03142,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03142,3,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03142,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_P03142,5,0)
   Gx_err = GX_DB_BindColLong( HStmt_P03142,6,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_P03142,7,0,30,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03148_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03148,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03148,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_P03148,3,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03147_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03147,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03147,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03146_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03146,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03146,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03145_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03145,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_P03145,2,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_P03145,3,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03144_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03144,1,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03144,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_P03144,3,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03144,4,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_P03144,5,GX_CS_LONG,GX_SQL_INTEGER,6,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_P03144,6,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,12,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03144,7,GX_CS_DOUBLE,GX_SQL_DECIMAL,14,2,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03144,8,GX_CS_DOUBLE,GX_SQL_DECIMAL,14,2,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_P03144,9,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,40,0)
   Gx_err = GX_DB_BindParmShort( HStmt_P03144,10,GX_CS_SHORT,GX_SQL_SMALLINT,1,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03143_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03143,1,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03143,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_P03143,3,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_P03143,4,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_P03143,5,GX_CS_LONG,GX_SQL_INTEGER,6,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDate( HStmt_P03143,6,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_P03143,7,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindParmP03142_01
   Gx_err = GX_DB_BindParmShort( HStmt_P03142,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDate( HStmt_P03142,2,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDate( HStmt_P03142,3,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
ENDPROC

***********************
PROCEDURE CD8Q0
***********************

   IF GXCONNECTED
   ENDIF
RETURN

***********************
PROCEDURE HL8Q2
***********************

   PARAMETERS Key_read, Attrinum
   PRIVATE GXLToBD
   GXLToBD = GXToBeDone
   GXToBeDone = ""
   DO CASE
      CASE Key_read <> 7 .AND. Key_read <> 8
         RETURN
      CASE Key_read = 8
         SET TOPIC TO  [PGenCblE]
         HELP
      OTHERWISE
         SET TOPIC TO  [PGenCblE]
         HELP
   ENDCASE
RETURN
