
***********************
* RlCltes
***********************

   PARAMETERS AV8Emprcod , AV9Fechasi , AV10Usuari , AV11Despro , AV12Haspro , AV13Entciv , AV14Entcui , AV15Entfvt , AV16Enttd , AV17Ctacli , AV18Entpib , AV19Entlgc , AV20Entlgf , AV21Entlgv , AV23Porsuc , Gx_out , AV37Ultima , AV41Entinh
   * Program generated by GeneXus Version 8_0_3-109
   * Description: listado de Clientes
   *       Xbase: FOXPRO
   *  Index Type: CDX
   *   Interface: WINDOWS
   *             Client/Server related information
   *         API: odbc
   *      Driver: qesqlserver
   *      Server: dagridb
   *   Data Base: Dagri

   #INCLUDE gxdatain.prg
   IF TYPE("GXToReadEvents") = "U"
      PUBLIC GXToReadEvents
   ENDIF
   GXToReadEvents = .T.
   LOCAL GXReadEvObj
   IF TYPE("GXReadEvents") = "U"
      PRIVATE GXReadEvents
      GXReadEvObj = .T.
   ELSE
      GXReadEvObj = GXReadEvents
   ENDIF
   GXReadEvents = .F.
   IF GXReadEvObj
   ENDIF
   PRIVATE gxHDC, GX_XPage, GX_YPage, GXPrn_Flag
   gxHDC = 0
   GX_XPage = 96
   GX_YPage = 96
   GXPrn_Flag = 0
   ON KEY LABEL ENTER
   IF ! GXReadEvObj
      SET SAFETY OFF
      SET BELL OFF
      SET REPROCESS TO 1
      IF SET("DATE") != "BRITISH"
         SET DATE BRITISH
      ENDIF
      SET EXACT ON
      SET CONFIRM ON
      DO GX_YrLmt WITH 19, 40
      IF SET("HOURS") != 24
         SET HOURS TO 24
      ENDIF
      SET READBORDER OFF
      IF SET("POINT") != "."
         SET POINT TO "."
         SET SEPARATOR TO ","
      ENDIF
      DO GX_DSSet
   ENDIF

   PRIVATE Buf_R04609_415DcVNroInt
   Buf_R04609_415DcVNroInt = 0
   PRIVATE Buf_R04609_2EmpCod
   Buf_R04609_2EmpCod = 0
   PRIVATE Buf_R04609_417DcVEntCod
   Buf_R04609_417DcVEntCod = 0
   PRIVATE Buf_R04609_421DcVFch
   Buf_R04609_421DcVFch = CTOD("  /  /  ")
   PRIVATE HStmt_R04609
   HStmt_R04609 = -1
   PRIVATE Buf_R04608_3426xPciAgR
   Buf_R04608_3426xPciAgR = 0
   PRIVATE Buf_R04608_3425xPciAgP
   Buf_R04608_3425xPciAgP = 0
   PRIVATE Buf_R04608_3096xPciIbA
   Buf_R04608_3096xPciIbA = 0.00
   PRIVATE Buf_R04608_2243xPciIbB
   Buf_R04608_2243xPciIbB = 0.00
   PRIVATE Buf_R04608_2100xPciCo2
   Buf_R04608_2100xPciCo2 = 0.0000
   PRIVATE Buf_R04608_2099xPciCoU
   Buf_R04608_2099xPciCoU = 0.0000
   PRIVATE Buf_R04608_2098xPcIDGI
   Buf_R04608_2098xPcIDGI = 0
   PRIVATE Buf_R04608_2097xPciIbr
   Buf_R04608_2097xPciIbr = 0.00
   PRIVATE Buf_R04608_2096xPciDsc
   Buf_R04608_2096xPciDsc = SPACE(40)
   PRIVATE Buf_R04608_2081xPciCod
   Buf_R04608_2081xPciCod = SPACE(4)
   PRIVATE Buf_R04608_2080xPaiCod
   Buf_R04608_2080xPaiCod = SPACE(4)
   PRIVATE HStmt_R04608
   HStmt_R04608 = -1
   PRIVATE Buf_R04607_2094xMunAlir
   Buf_R04607_2094xMunAlir = 0.00
   PRIVATE Buf_R04607_2093xMunAlic
   Buf_R04607_2093xMunAlic = 0.00
   PRIVATE Buf_R04607_2092xMunAliH
   Buf_R04607_2092xMunAliH = 0.00
   PRIVATE Buf_R04607_2091xMunRic
   Buf_R04607_2091xMunRic = 0.00
   PRIVATE Buf_R04607_2090xMunCar
   Buf_R04607_2090xMunCar = 0.00
   PRIVATE Buf_R04607_2089xMunHue
   Buf_R04607_2089xMunHue = 0.00
   PRIVATE Buf_R04607_2088xMunMin
   Buf_R04607_2088xMunMin = 0.00
   PRIVATE Buf_R04607_2087xMunNRell
   Buf_R04607_2087xMunNRell = 0.00
   PRIVATE Buf_R04607_2086xMunRell
   Buf_R04607_2086xMunRell = 0.00
   PRIVATE Buf_R04607_2085xMunTap
   Buf_R04607_2085xMunTap = 0.00
   PRIVATE Buf_R04607_2084xMunDsc
   Buf_R04607_2084xMunDsc = SPACE(70)
   PRIVATE Buf_R04607_2083xMunAba
   Buf_R04607_2083xMunAba = 0.0000
   PRIVATE Buf_R04607_2082xMunCod
   Buf_R04607_2082xMunCod = SPACE(4)
   PRIVATE Buf_R04607_2081xPciCod
   Buf_R04607_2081xPciCod = SPACE(4)
   PRIVATE Buf_R04607_2080xPaiCod
   Buf_R04607_2080xPaiCod = SPACE(4)
   PRIVATE HStmt_R04607
   HStmt_R04607 = -1
   PRIVATE Buf_R04606_176EntLgCod
   Buf_R04606_176EntLgCod = 0
   PRIVATE Buf_R04606_178EntLgDom
   Buf_R04606_178EntLgDom = SPACE(40)
   PRIVATE Buf_R04606_185EntLgCont
   Buf_R04606_185EntLgCont = SPACE(40)
   PRIVATE Buf_R04606_1076Entlgloc
   Buf_R04606_1076Entlgloc = SPACE(20)
   PRIVATE Buf_R04606_186EntLgTel
   Buf_R04606_186EntLgTel = SPACE(40)
   PRIVATE Buf_R04606_189EntLgVdrNo
   Buf_R04606_189EntLgVdrNo = SPACE(40)
   PRIVATE Buf_R04606_1335EntLgCIvDs
   Buf_R04606_1335EntLgCIvDs = SPACE(40)
   PRIVATE Buf_R04606_192EntLgOrden
   Buf_R04606_192EntLgOrden = SPACE(40)
   PRIVATE Buf_R04606_1439EntLgIBRet
   Buf_R04606_1439EntLgIBRet = SPACE(1)
   PRIVATE Buf_R04606_182EntLgMunCo
   Buf_R04606_182EntLgMunCo = SPACE(4)
   PRIVATE Buf_R04606_180EntLgPciCo
   Buf_R04606_180EntLgPciCo = SPACE(4)
   PRIVATE Buf_R04606_155EntCont
   Buf_R04606_155EntCont = SPACE(40)
   PRIVATE Buf_R04606_158EntPaiDsc
   Buf_R04606_158EntPaiDsc = SPACE(40)
   PRIVATE Buf_R04606_163EntPos
   Buf_R04606_163EntPos = SPACE(10)
   PRIVATE Buf_R04606_156EntDom
   Buf_R04606_156EntDom = SPACE(40)
   PRIVATE Buf_R04606_167EntEMa
   Buf_R04606_167EntEMa = SPACE(40)
   PRIVATE Buf_R04606_168EntFpa
   Buf_R04606_168EntFpa = 0
   PRIVATE Buf_R04606_174EntDesc
   Buf_R04606_174EntDesc = 0.00
   PRIVATE Buf_R04606_1475EntPIBFR
   Buf_R04606_1475EntPIBFR = SPACE(1)
   PRIVATE Buf_R04606_1685EntCred
   Buf_R04606_1685EntCred = 0.00
   PRIVATE Buf_R04606_153EntRaz
   Buf_R04606_153EntRaz = SPACE(40)
   PRIVATE Buf_R04606_164EntTel
   Buf_R04606_164EntTel = SPACE(40)
   PRIVATE Buf_R04606_165EntFax
   Buf_R04606_165EntFax = SPACE(40)
   PRIVATE Buf_R04606_166EntCui
   Buf_R04606_166EntCui = 0
   PRIVATE Buf_R04606_172EntCIvDsc
   Buf_R04606_172EntCIvDsc = SPACE(40)
   PRIVATE Buf_R04606_1469CtaCliCod
   Buf_R04606_1469CtaCliCod = 0
   PRIVATE Buf_R04606_2078EntCPIB
   Buf_R04606_2078EntCPIB = 0.00
   PRIVATE Buf_R04606_3270EntDes1
   Buf_R04606_3270EntDes1 = 0.00
   PRIVATE Buf_R04606_161EntMunCod
   Buf_R04606_161EntMunCod = SPACE(4)
   PRIVATE Buf_R04606_159EntPciCod
   Buf_R04606_159EntPciCod = SPACE(4)
   PRIVATE Buf_R04606_1334EntLgCIvCo
   Buf_R04606_1334EntLgCIvCo = 0
   PRIVATE Buf_R04606_188EntLgVdrCo
   Buf_R04606_188EntLgVdrCo = 0
   PRIVATE Buf_R04606_187EntLgFVt
   Buf_R04606_187EntLgFVt = SPACE(2)
   PRIVATE Buf_R04606_150EntGruTip
   Buf_R04606_150EntGruTip = SPACE(2)
   PRIVATE Buf_R04606_120EntCod
   Buf_R04606_120EntCod = 0
   PRIVATE Buf_R04606_2EmpCod
   Buf_R04606_2EmpCod = 0
   PRIVATE Buf_R04606_171EntCIvCod
   Buf_R04606_171EntCIvCod = 0
   PRIVATE Buf_R04606_157EntPaiCod
   Buf_R04606_157EntPaiCod = SPACE(4)
   PRIVATE HStmt_R04606
   HStmt_R04606 = -1
   PRIVATE Buf_R04605_1038VdrNom
   Buf_R04605_1038VdrNom = SPACE(40)
   PRIVATE Buf_R04605_1037VdrCod
   Buf_R04605_1037VdrCod = 0
   PRIVATE Buf_R04605_2EmpCod
   Buf_R04605_2EmpCod = 0
   PRIVATE HStmt_R04605
   HStmt_R04605 = -1
   PRIVATE Buf_R04604_89CIvDsc
   Buf_R04604_89CIvDsc = SPACE(40)
   PRIVATE Buf_R04604_88CIvCod
   Buf_R04604_88CIvCod = 0
   PRIVATE HStmt_R04604
   HStmt_R04604 = -1
   PRIVATE Buf_R04603_89CIvDsc
   Buf_R04603_89CIvDsc = SPACE(40)
   PRIVATE Buf_R04603_88CIvCod
   Buf_R04603_88CIvCod = 0
   PRIVATE HStmt_R04603
   HStmt_R04603 = -1
   PRIVATE Buf_R04602_155EntCont
   Buf_R04602_155EntCont = SPACE(40)
   PRIVATE Buf_R04602_158EntPaiDsc
   Buf_R04602_158EntPaiDsc = SPACE(40)
   PRIVATE Buf_R04602_163EntPos
   Buf_R04602_163EntPos = SPACE(10)
   PRIVATE Buf_R04602_156EntDom
   Buf_R04602_156EntDom = SPACE(40)
   PRIVATE Buf_R04602_164EntTel
   Buf_R04602_164EntTel = SPACE(40)
   PRIVATE Buf_R04602_165EntFax
   Buf_R04602_165EntFax = SPACE(40)
   PRIVATE Buf_R04602_167EntEMa
   Buf_R04602_167EntEMa = SPACE(40)
   PRIVATE Buf_R04602_168EntFpa
   Buf_R04602_168EntFpa = 0
   PRIVATE Buf_R04602_172EntCIvDsc
   Buf_R04602_172EntCIvDsc = SPACE(40)
   PRIVATE Buf_R04602_174EntDesc
   Buf_R04602_174EntDesc = 0.00
   PRIVATE Buf_R04602_1685EntCred
   Buf_R04602_1685EntCred = 0.00
   PRIVATE Buf_R04602_161EntMunCod
   Buf_R04602_161EntMunCod = SPACE(4)
   PRIVATE Buf_R04602_159EntPciCod
   Buf_R04602_159EntPciCod = SPACE(4)
   PRIVATE Buf_R04602_171EntCIvCod
   Buf_R04602_171EntCIvCod = 0
   PRIVATE Buf_R04602_166EntCui
   Buf_R04602_166EntCui = 0
   PRIVATE Buf_R04602_175EntFVt
   Buf_R04602_175EntFVt = SPACE(2)
   PRIVATE Buf_R04602_1267Enttd
   Buf_R04602_1267Enttd = SPACE(1)
   PRIVATE Buf_R04602_1469CtaCliCod
   Buf_R04602_1469CtaCliCod = 0
   PRIVATE Buf_R04602_1475EntPIBFR
   Buf_R04602_1475EntPIBFR = SPACE(1)
   PRIVATE Buf_R04602_153EntRaz
   Buf_R04602_153EntRaz = SPACE(40)
   PRIVATE Buf_R04602_1717EntInhab
   Buf_R04602_1717EntInhab = SPACE(1)
   PRIVATE Buf_R04602_120EntCod
   Buf_R04602_120EntCod = 0
   PRIVATE Buf_R04602_150EntGruTip
   Buf_R04602_150EntGruTip = SPACE(2)
   PRIVATE Buf_R04602_2EmpCod
   Buf_R04602_2EmpCod = 0
   PRIVATE Buf_R04602_157EntPaiCod
   Buf_R04602_157EntPaiCod = SPACE(4)
   PRIVATE HStmt_R04602
   HStmt_R04602 = -1

   PRIVATE UserCancel, GX_newwin, GX_eject, GX_prn_defa, GX_env_def, GX_retp
   UserCancel = .F.
   GX_newwin = "GXDummyWin"
   GX_eject = .T.
   GX_XProp = 1
   gx_prn_defa = ""
   gx_env_def = .f.
   GX_retp = 0
   PRIVATE gx_oldDVal
   gx_oldDVal = CTOD("  /  /  ")

   PRIVATE currSoapErr, currSoapErrmsg
   currSoapErr = 0
   currSoapErrmsg = ""
   PRIVATE GX_pg_started
   GX_pg_started = .F.
   * Variables Definition
   PRIVATE AV8Emprcod
   PRIVATE AV9Fechasi
   PRIVATE AV10Usuari
   PRIVATE AV11Despro
   PRIVATE AV12Haspro
   PRIVATE AV13Entciv
   PRIVATE AV14Entcui
   PRIVATE AV15Entfvt
   PRIVATE AV16Enttd
   PRIVATE AV17Ctacli
   PRIVATE AV18Entpib
   PRIVATE AV19Entlgc
   PRIVATE AV20Entlgf
   PRIVATE AV21Entlgv
   PRIVATE AV23Porsuc
   PRIVATE Gx_out
   PRIVATE AV37Ultima
   PRIVATE AV41Entinh
   PRIVATE R3410DcvDe
   R3410DcvDe = 0.00
   PRIVATE R3409DcvDe
   R3409DcvDe = 0.00
   PRIVATE R3332DcvMo
   R3332DcvMo = SPACE(20)
   PRIVATE R3322DcvNr
   R3322DcvNr = 0
   PRIVATE R3321DcvSr
   R3321DcvSr = 0
   PRIVATE R3320DcvTr
   R3320DcvTr = SPACE(3)
   PRIVATE R3319DcvPe
   R3319DcvPe = 0
   PRIVATE R3302DcvFe
   R3302DcvFe = CTOD("  /  /  ")
   PRIVATE R3301DcvSo
   R3301DcvSo = SPACE(13)
   PRIVATE R3277DcvLE
   R3277DcvLE = 0.00
   PRIVATE R3272DcvDe
   R3272DcvDe = 0.00
   PRIVATE R3219DcvCB
   R3219DcvCB = SPACE(22)
   PRIVATE R3218DcvTD
   R3218DcvTD = 0
   PRIVATE R3184DcvOb
   R3184DcvOb = SPACE(400)
   PRIVATE R3152DcvIm
   R3152DcvIm = 0
   PRIVATE R3151DcvCa
   R3151DcvCa = CTOD("  /  /  ")
   PRIVATE R3150DcvCa
   R3150DcvCa = SPACE(10)
   PRIVATE R3149DcvNr
   R3149DcvNr = 0
   PRIVATE R3125DcvFE
   R3125DcvFE = CTOD("  /  /  ")
   PRIVATE R3123DcvId
   R3123DcvId = SPACE(14)
   PRIVATE R3064DcvSe
   R3064DcvSe = SPACE(100)
   PRIVATE R3063DcvSe
   R3063DcvSe = CTOD("  /  /  ")
   PRIVATE R3062DcvSe
   R3062DcvSe = 0
   PRIVATE R3005DcvBa
   R3005DcvBa = 0.00
   PRIVATE R2961DcvFC
   R2961DcvFC = CTOD("  /  /  ")
   PRIVATE R2941DcvFc
   R2941DcvFc = 0.00
   PRIVATE R2940DcvFc
   R2940DcvFc = 0.00
   PRIVATE R2939DcvFa
   R2939DcvFa = 0
   PRIVATE R2923DcvOt
   R2923DcvOt = SPACE(100)
   PRIVATE R2909DcvFv
   R2909DcvFv = SPACE(20)
   PRIVATE R2615dcvPa
   R2615dcvPa = 0.00
   PRIVATE R2496DCvOr
   R2496DCvOr = 0
   PRIVATE R2342DcvBc
   R2342DcvBc = SPACE(10)
   PRIVATE R2325DcvEm
   R2325DcvEm = SPACE(16)
   PRIVATE R2320DcvId
   R2320DcvId = 0
   PRIVATE R2319DcvCA
   R2319DcvCA = SPACE(400)
   PRIVATE R2318DcvCA
   R2318DcvCA = SPACE(2)
   PRIVATE R2314DcvCA
   R2314DcvCA = CTOD("  /  /  ")
   PRIVATE R2313DcvCA
   R2313DcvCA = SPACE(15)
   PRIVATE R2230DcvFc
   R2230DcvFc = CTOD("  /  /  ")
   PRIVATE R2227DcvFV
   R2227DcvFV = SPACE(3)
   PRIVATE R2226DCVNr
   R2226DCVNr = 0
   PRIVATE R2154DcvCh
   R2154DcvCh = 0
   PRIVATE R1835DcvPa
   R1835DcvPa = 0
   PRIVATE R1813DcvEf
   R1813DcvEf = 0.00
   PRIVATE R1597DcVSe
   R1597DcVSe = SPACE(4029)
   PRIVATE R1596DcVSe
   R1596DcVSe = SPACE(40)
   PRIVATE R1564DcvSe
   R1564DcvSe = CTOD("  /  /  ")
   PRIVATE R1563DcvSe
   R1563DcvSe = 0
   PRIVATE R1473DcvCt
   R1473DcvCt = 0
   PRIVATE R1465DcvVe
   R1465DcvVe = 0
   PRIVATE R1428DcvCo
   R1428DcvCo = 0.0000
   PRIVATE R1427DcvMo
   R1427DcvMo = 0
   PRIVATE R1336DcVTo
   R1336DcVTo = 0.00
   PRIVATE R1325DcvOr
   R1325DcvOr = 0
   PRIVATE R1208DcvTi
   R1208DcvTi = SPACE(2)
   PRIVATE R472DcVSig
   R472DcVSig = 0
   PRIVATE R471DcVFCo
   R471DcVFCo = CTOD("  /  /  ")
   PRIVATE R470DcVTot
   R470DcVTot = 0.00
   PRIVATE R468DcVNet
   R468DcVNet = 0.00
   PRIVATE R467DcVCta
   R467DcVCta = SPACE(1)
   PRIVATE R466DcVEst
   R466DcVEst = 0
   PRIVATE R465DcVFv
   R465DcVFv = CTOD("  /  /  ")
   PRIVATE R464DcVTot
   R464DcVTot = 0.00
   PRIVATE R463DcVNet
   R463DcVNet = 0.00
   PRIVATE R444DcVFat
   R444DcVFat = SPACE(10)
   PRIVATE R443DcVIng
   R443DcVIng = SPACE(10)
   PRIVATE R442DcVPid
   R442DcVPid = SPACE(40)
   PRIVATE R441DcVOrd
   R441DcVOrd = SPACE(16)
   PRIVATE R440DcVObs
   R440DcVObs = SPACE(1)
   PRIVATE R439DcVObs
   R439DcVObs = SPACE(40)
   PRIVATE R437DcVDes
   R437DcVDes = 0.00
   PRIVATE R433DcVFTl
   R433DcVFTl = 0
   PRIVATE R432DcVTLi
   R432DcVTLi = 0
   PRIVATE R431DcVFch
   R431DcVFch = CTOD("  /  /  ")
   PRIVATE R430DcVNro
   R430DcVNro = 0
   PRIVATE R429DcVNro
   R429DcVNro = 0
   PRIVATE R428DcVSuc
   R428DcVSuc = 0
   PRIVATE R427DcVSer
   R427DcVSer = SPACE(1)
   PRIVATE R426DcVTip
   R426DcVTip = SPACE(4)
   PRIVATE R425DcVNro
   R425DcVNro = 0
   PRIVATE R424DcVSuc
   R424DcVSuc = 0
   PRIVATE R423DcVSer
   R423DcVSer = SPACE(1)
   PRIVATE R422DcVTip
   R422DcVTip = SPACE(4)
   PRIVATE R419DcVEnt
   R419DcVEnt = 0
   PRIVATE R416DcVEnt
   R416DcVEnt = SPACE(2)
   PRIVATE R415DcVNro
   R415DcVNro = 0
   PRIVATE R3007EntLg
   R3007EntLg = CTOD("  /  /  ")
   PRIVATE R3006EntLg
   R3006EntLg = 0
   PRIVATE R2822Entlg
   R2822Entlg = SPACE(40)
   PRIVATE R2817EntLg
   R2817EntLg = SPACE(10)
   PRIVATE R2504EntLg
   R2504EntLg = 0
   PRIVATE R2340EntLg
   R2340EntLg = SPACE(10)
   PRIVATE R2009EntLg
   R2009EntLg = SPACE(10)
   PRIVATE R1926EntLg
   R1926EntLg = SPACE(1)
   PRIVATE R1917EntLg
   R1917EntLg = SPACE(15)
   PRIVATE R1887entLg
   R1887entLg = SPACE(30)
   PRIVATE R1886EntLg
   R1886EntLg = SPACE(1)
   PRIVATE R1845EntLg
   R1845EntLg = 0
   PRIVATE R179EntLgP
   R179EntLgP = SPACE(4)
   PRIVATE R177EntLgD
   R177EntLgD = SPACE(30)
   PRIVATE R3510VdrPr
   R3510VdrPr = 0
   PRIVATE R3509VdrPr
   R3509VdrPr = SPACE(2)
   PRIVATE R3393VdrDD
   R3393VdrDD = CTOD("  /  /  ")
   PRIVATE R2956VdrRo
   R2956VdrRo = SPACE(1)
   PRIVATE R1934VdrCC
   R1934VdrCC = 0.00
   PRIVATE R1042VdrCu
   R1042VdrCu = 0
   PRIVATE R1041VdrOb
   R1041VdrOb = SPACE(40)
   PRIVATE R1040VdrTe
   R1040VdrTe = SPACE(40)
   PRIVATE R1039VdrDi
   R1039VdrDi = SPACE(40)
   PRIVATE R1438CivIB
   R1438CivIB = 0.00
   PRIVATE R1429CIVII
   R1429CIVII = 0.00
   PRIVATE R91CIvSta
   R91CIvSta = 0.00
   PRIVATE R90CIvNor
   R90CIvNor = 0.00
   PRIVATE R3606EntDe
   R3606EntDe = 0
   PRIVATE R3442EntAc
   R3442EntAc = 0
   PRIVATE R3441EntMa
   R3441EntMa = 0
   PRIVATE R3408EntDe
   R3408EntDe = 0.00
   PRIVATE R3407EntDe
   R3407EntDe = 0.00
   PRIVATE R3323EntLi
   R3323EntLi = 0
   PRIVATE R3313EntAR
   R3313EntAR = 0
   PRIVATE R3306EntCR
   R3306EntCR = 0
   PRIVATE R3305EntDb
   R3305EntDb = 0
   PRIVATE R3303EntEn
   R3303EntEn = SPACE(1)
   PRIVATE R3275EntLE
   R3275EntLE = 0.00
   PRIVATE R3269EntPa
   R3269EntPa = 0
   PRIVATE R3267EntLe
   R3267EntLe = 0
   PRIVATE R3246EntBo
   R3246EntBo = 0
   PRIVATE R3197EntLi
   R3197EntLi = 0.00
   PRIVATE R3196EntPr
   R3196EntPr = 0
   PRIVATE R3195EntAl
   R3195EntAl = 0.00
   PRIVATE R3194EntAl
   R3194EntAl = 0.0000
   PRIVATE R3193EntAl
   R3193EntAl = 0
   PRIVATE R3160EntMo
   R3160EntMo = SPACE(1)
   PRIVATE R3122EntKr
   R3122EntKr = 0
   PRIVATE R3057EntLa
   R3057EntLa = SPACE(1)
   PRIVATE R3046EntRe
   R3046EntRe = CTOD("  /  /  ")
   PRIVATE R3034EntEx
   R3034EntEx = 0
   PRIVATE R3033EntCa
   R3033EntCa = SPACE(1)
   PRIVATE R3020CPaCo
   R3020CPaCo = 0
   PRIVATE R3014EntIB
   R3014EntIB = 0
   PRIVATE R3010EntPr
   R3010EntPr = CTOD("  /  /  ")
   PRIVATE R3009EntPr
   R3009EntPr = 0
   PRIVATE R2992EntIb
   R2992EntIb = SPACE(1)
   PRIVATE R2937EntCP
   R2937EntCP = 0
   PRIVATE R2612EntRe
   R2612EntRe = 0
   PRIVATE R2611EntRe
   R2611EntRe = 0
   PRIVATE R2588EntRI
   R2588EntRI = 0.00
   PRIVATE R2510EntTD
   R2510EntTD = SPACE(2)
   PRIVATE R2339EntNo
   R2339EntNo = 0
   PRIVATE R2276EntFV
   R2276EntFV = SPACE(3)
   PRIVATE R2248EntGa
   R2248EntGa = CTOD("  /  /  ")
   PRIVATE R2247EntGa
   R2247EntGa = CTOD("  /  /  ")
   PRIVATE R2246EntGa
   R2246EntGa = 0.00
   PRIVATE R2224EntRu
   R2224EntRu = SPACE(20)
   PRIVATE R2223EntRu
   R2223EntRu = SPACE(4)
   PRIVATE R2156EntEs
   R2156EntEs = SPACE(1)
   PRIVATE R2102EntTL
   R2102EntTL = SPACE(2)
   PRIVATE R2079EntCR
   R2079EntCR = 0.00
   PRIVATE R1993EntIn
   R1993EntIn = SPACE(40)
   PRIVATE R1963EntNo
   R1963EntNo = 0
   PRIVATE R1927EntPr
   R1927EntPr = SPACE(1)
   PRIVATE R1922EntRe
   R1922EntRe = CTOD("  /  /  ")
   PRIVATE R1916EntEA
   R1916EntEA = SPACE(15)
   PRIVATE R1877EntAb
   R1877EntAb = 0
   PRIVATE R1832EntId
   R1832EntId = SPACE(11)
   PRIVATE R1831entCt
   R1831entCt = SPACE(1)
   PRIVATE R1809EntCu
   R1809EntCu = SPACE(10)
   PRIVATE R1804EntCu
   R1804EntCu = SPACE(1)
   PRIVATE R1745entCt
   R1745entCt = SPACE(1)
   PRIVATE R1734entMe
   R1734entMe = SPACE(4095)
   PRIVATE R1718entIn
   R1718entIn = SPACE(30)
   PRIVATE R1689EntSe
   R1689EntSe = SPACE(1)
   PRIVATE R1676EntMe
   R1676EntMe = SPACE(1)
   PRIVATE R1660EntCr
   R1660EntCr = SPACE(1)
   PRIVATE R1477EntDc
   R1477EntDc = SPACE(1)
   PRIVATE R1459EntSU
   R1459EntSU = SPACE(1)
   PRIVATE R1432EntIB
   R1432EntIB = SPACE(1)
   PRIVATE R1431EntIB
   R1431EntIB = SPACE(15)
   PRIVATE R1430EntIB
   R1430EntIB = SPACE(15)
   PRIVATE R1422EntOb
   R1422EntOb = SPACE(40)
   PRIVATE R1323EntOr
   R1323EntOr = 0
   PRIVATE R842EntRet
   R842EntRet = SPACE(1)
   PRIVATE R841EntGCo
   R841EntGCo = SPACE(1)
   PRIVATE R840EntLoc
   R840EntLoc = SPACE(40)
   PRIVATE R173EntObs
   R173EntObs = SPACE(40)
   PRIVATE R170EntOrd
   R170EntOrd = SPACE(50)
   PRIVATE R169EntNIm
   R169EntNIm = SPACE(12)
   PRIVATE R154EntFan
   R154EntFan = SPACE(40)
   PRIVATE R151EntGru
   R151EntGru = SPACE(3)
   PRIVATE R157EntPai
   R157EntPai = SPACE(4)
   PRIVATE R2094xMunA
   R2094xMunA = 0.00
   PRIVATE R2093xMunA
   R2093xMunA = 0.00
   PRIVATE R2092xMunA
   R2092xMunA = 0.00
   PRIVATE R2091xMunR
   R2091xMunR = 0.00
   PRIVATE R2090xMunC
   R2090xMunC = 0.00
   PRIVATE R2089xMunH
   R2089xMunH = 0.00
   PRIVATE R2088xMunM
   R2088xMunM = 0.00
   PRIVATE R2087xMunN
   R2087xMunN = 0.00
   PRIVATE R2086xMunR
   R2086xMunR = 0.00
   PRIVATE R2085xMunT
   R2085xMunT = 0.00
   PRIVATE R3426xPciA
   R3426xPciA = 0
   PRIVATE R3425xPciA
   R3425xPciA = 0
   PRIVATE R3096xPciI
   R3096xPciI = 0.00
   PRIVATE R2243xPciI
   R2243xPciI = 0.00
   PRIVATE R2100xPciC
   R2100xPciC = 0.0000
   PRIVATE R2099xPciC
   R2099xPciC = 0.0000
   PRIVATE R2098xPcID
   R2098xPcID = 0
   PRIVATE R2097xPciI
   R2097xPciI = 0.00
   PRIVATE Gx_line
   Gx_line = 0
   PRIVATE R421DcVFch
   R421DcVFch = CTOD("  /  /  ")
   PRIVATE R417DcVEnt
   R417DcVEnt = 0
   PRIVATE R2096xPciD
   R2096xPciD = SPACE(40)
   PRIVATE R2080xPaiC
   R2080xPaiC = SPACE(4)
   PRIVATE R2081xPciC
   R2081xPciC = SPACE(4)
   PRIVATE R2082xMunC
   R2082xMunC = SPACE(4)
   PRIVATE R2084xMunD
   R2084xMunD = SPACE(70)
   PRIVATE R2083xMunA
   R2083xMunA = 0.0000
   PRIVATE R187EntLgF
   R187EntLgF = SPACE(2)
   PRIVATE R188EntLgV
   R188EntLgV = 0
   PRIVATE R1334EntLg
   R1334EntLg = 0
   PRIVATE R3270EntDe
   R3270EntDe = 0.00
   PRIVATE R2078EntCP
   R2078EntCP = 0.00
   PRIVATE R180EntLgP
   R180EntLgP = SPACE(4)
   PRIVATE R182EntLgM
   R182EntLgM = SPACE(4)
   PRIVATE R1439EntLg
   R1439EntLg = SPACE(1)
   PRIVATE R192EntLgO
   R192EntLgO = SPACE(40)
   PRIVATE R1335EntLg
   R1335EntLg = SPACE(40)
   PRIVATE R189EntLgV
   R189EntLgV = SPACE(40)
   PRIVATE R186EntLgT
   R186EntLgT = SPACE(40)
   PRIVATE R1076Entlg
   R1076Entlg = SPACE(20)
   PRIVATE R185EntLgC
   R185EntLgC = SPACE(40)
   PRIVATE R178EntLgD
   R178EntLgD = SPACE(40)
   PRIVATE R176EntLgC
   R176EntLgC = 0
   PRIVATE R1037VdrCo
   R1037VdrCo = 0
   PRIVATE R1038VdrNo
   R1038VdrNo = SPACE(40)
   PRIVATE R88CIvCod
   R88CIvCod = 0
   PRIVATE R89CIvDsc
   R89CIvDsc = SPACE(40)
   PRIVATE R2EmpCod
   R2EmpCod = 0
   PRIVATE R150EntGru
   R150EntGru = SPACE(2)
   PRIVATE R120EntCod
   R120EntCod = 0
   PRIVATE R1717EntIn
   R1717EntIn = SPACE(1)
   PRIVATE R153EntRaz
   R153EntRaz = SPACE(40)
   PRIVATE R1475EntPI
   R1475EntPI = SPACE(1)
   PRIVATE R1469CtaCl
   R1469CtaCl = 0
   PRIVATE R1267Enttd
   R1267Enttd = SPACE(1)
   PRIVATE R175EntFVt
   R175EntFVt = SPACE(2)
   PRIVATE R166EntCui
   R166EntCui = 0
   PRIVATE R171EntCIv
   R171EntCIv = 0
   PRIVATE R159EntPci
   R159EntPci = SPACE(4)
   PRIVATE R161EntMun
   R161EntMun = SPACE(4)
   PRIVATE R1685EntCr
   R1685EntCr = 0.00
   PRIVATE R174EntDes
   R174EntDes = 0.00
   PRIVATE R172EntCIv
   R172EntCIv = SPACE(40)
   PRIVATE R168EntFpa
   R168EntFpa = 0
   PRIVATE R167EntEMa
   R167EntEMa = SPACE(40)
   PRIVATE R165EntFax
   R165EntFax = SPACE(40)
   PRIVATE R164EntTel
   R164EntTel = SPACE(40)
   PRIVATE R156EntDom
   R156EntDom = SPACE(40)
   PRIVATE R163EntPos
   R163EntPos = SPACE(10)
   PRIVATE R158EntPai
   R158EntPai = SPACE(40)
   PRIVATE R155EntCon
   R155EntCon = SPACE(40)
   PRIVATE Gx_time
   Gx_time = SUBSTR(TIME(), 1, 8)
   PRIVATE Gx_page
   Gx_page = 0
   PRIVATE Gx_emsg
   Gx_emsg = SPACE(70)
   PRIVATE Gx_err
   Gx_err = 0
   PRIVATE RV42Titulo
   RV42Titulo = SPACE(20)
   PRIVATE RV40Ok
   RV40Ok = 0
   PRIVATE RV39Entcod
   RV39Entcod = 0
   PRIVATE RV38Entgru
   RV38Entgru = SPACE(2)
   PRIVATE RV36Munaba
   RV36Munaba = 0.0000
   PRIVATE RV35Muncod
   RV35Muncod = SPACE(4)
   PRIVATE RV34Entpci
   RV34Entpci = SPACE(40)
   PRIVATE RV33Mundsc
   RV33Mundsc = SPACE(70)
   PRIVATE RV32Pcidsc
   RV32Pcidsc = SPACE(40)
   PRIVATE RV31Pcicod
   RV31Pcicod = SPACE(4)
   PRIVATE RV30Entmun
   RV30Entmun = SPACE(70)
   PRIVATE RV29Emprno
   RV29Emprno = SPACE(30)
   PRIVATE RV28Usucod
   RV28Usucod = SPACE(10)
   PRIVATE RV27Txt1
   RV27Txt1 = SPACE(250)
   PRIVATE RV26Txt
   RV26Txt = SPACE(250)
   PRIVATE RV25Tipode
   RV25Tipode = SPACE(9)
   PRIVATE RV24Formav
   RV24Formav = SPACE(7)
   PRIVATE RV22Primer
   RV22Primer = SPACE(1)
   * Level Flags
   PRIVATE LEVEL2
   LEVEL2 = .F.
   PRIVATE LEVEL3
   LEVEL3 = .F.
   PRIVATE LEVEL4
   LEVEL4 = .F.
   PRIVATE LEVEL5
   LEVEL5 = .F.
   PRIVATE LEVEL6
   LEVEL6 = .F.
   PRIVATE LEVEL7
   LEVEL7 = .F.
   PRIVATE LEVEL8
   LEVEL8 = .F.
   PRIVATE LEVEL9
   LEVEL9 = .F.
   PRIVATE LEVEL10
   LEVEL10 = .F.
   PRIVATE LEVEL1
   LEVEL1 = .F.
   * Cursors Definition
   PRIVATE GX_OP42
   GX_OP42 = .F.
   PRIVATE GX_REC42
   GX_REC42 = 0
   PRIVATE GOXPCIAS
   GOXPCIAS = .F.
   PRIVATE GXXPCIAS
   GXXPCIAS = 0
   PRIVATE GOXMUNI
   GOXMUNI = .F.
   PRIVATE GXXMUNI
   GXXMUNI = 0
   PRIVATE GX_OP16
   GX_OP16 = .F.
   PRIVATE GX_REC16
   GX_REC16 = 0
   PRIVATE GX_OP15
   GX_OP15 = .F.
   PRIVATE GX_REC15
   GX_REC15 = 0
   PRIVATE GX_OP576
   GX_OP576 = .F.
   PRIVATE GX_REC576
   GX_REC576 = 0
   PRIVATE GX_OP590
   GX_OP590 = .F.
   PRIVATE GX_REC590
   GX_REC590 = 0
   PRIVATE GX_OP611
   GX_OP611 = .F.
   PRIVATE GX_REC611
   GX_REC611 = 0
   PRIVATE GX_OP525
   GX_OP525 = .F.
   PRIVATE GX_REC525
   GX_REC525 = 0
   PRIVATE GX_OP112
   GX_OP112 = .F.
   PRIVATE GX_REC112
   GX_REC112 = 0
   PRIVATE GX_OP10
   GX_OP10 = .F.
   PRIVATE GX_REC10
   GX_REC10 = 0
   * Gx formulas
   Gx_line = 0
   Gx_time = SUBSTR(TIME(), 1, 8)
   Gx_err = 0
   * Device settings
   PRIVATE old_area, rpt_name, RptView
   old_area = 0
   rpt_name = " "
   RptView = .F.
   PRIVATE gx_dll_set
   gx_dll_set = .F.
   Gx_dvc = "PRN"
   gxPrnObj = CREATEOBJECT( "GxRptDLL" )
   Gx_prn_ini = "GXPRN.INI"
   Gx_prn_form = ""
   Gx_prn_name = ""
   gxPrnObj.GxRptWndMaximize( )
   gxPrnObj.GXRVSetLanguage( 'spa' )
   DO CASE
      CASE Gx_out = "PRN"
         gxPType = 0
      CASE Gx_out = "FIL"
         gxPType = 2
      OTHERWISE
         gxPType = 1
   ENDCASE
   gxAuxHDC = GxHDC
   GXAux_XPage = GX_XPage
   GXAux_YPage = GX_YPage
   GXPrn_Flag = gxPrnObj.GXPrInit( @gxAuxHDC, gxPType, @GXAux_XPage, @GXAux_YPage, 0, GX_prn_ini, GX_prn_form, GX_prn_name, 2 , 2 , 9 , 16838 , 11906 , 0 , 1 , 1 , 0 , 1 , 1 )
   GxHDC = gxAuxHDC
   GX_XPage = GXAux_XPage
   GX_YPage = GXAux_YPage
   gxPrnObj.GxSetDocName( GxHDC , "listado de Clientes" )
   IF GXPrn_Flag = 0
      GXAuxPrn_Flag = GXPrn_Flag
      gxPrnObj.GXEndPrn( gxHDC , @GXAuxPrn_Flag)
      GXPrn_Flag = GXAuxPrn_Flag
      RETURN
   ENDIF
   GX_XPage= gxPrnObj.GxGetPageSizeX( GxHDC )
   GX_YPage= gxPrnObj.GxGetPageSizeY( GxHDC )
   gx_dll_set = .T.
   Gx_dvc = "PRN"
   GXsXPR = GXFMET(6,"Courier New",10)
   GXsYPR = 16
   P_lines = GX_YPage - ( 6 * GXsYPR )
   M_top = 0 * GXsYPR
   DEFINE WINDOW _WMSG AT 1,1 SIZE 0,0
   DO GX_MSGW WITH "Imprimiendo..."
   Gx_line = 1
   LEVEL1 = .T.
   Gx_line = P_lines + 3
   IF AV12Haspro = 0
      AV12Haspro = 999999
   ENDIF
   DO RLeeEmp WITH AV8Emprcod , RV29Emprno
   RV38Entgru = "CL"
   DO CASE
      CASE AV41Entinh = "T"
         RV42Titulo = " "
      CASE AV41Entinh = "N"
         RV42Titulo = "Datos de Clientes Habilitados"
      CASE AV41Entinh = "S"
         RV42Titulo = "Datos de Clientes Inhabilitados"
   ENDCASE
   LEVEL3 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04602" , @HStmt_R04602 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04602","",GX_CURSOR_TYPE_READONLY,@HStmt_R04602) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT T1.[EntPaiCod] AS EntPaiCod, T1.[EmpCod], T1.[EntGruTip], T1.[EntCod], T1.[EntInhab], "
      cmdbuf = cmdbuf + "  T1.[EntRaz], T1.[EntPIBFR], T1.[CtaCliCod], T1.[Enttd], T1.[EntFVt], T1.[EntCui], "
      cmdbuf = cmdbuf + "  T1.[EntCIvCod] AS EntCIvCod, T1.[EntPciCod], T1.[EntMunCod], T1.[EntCred], T1.[EntDesc], "
      cmdbuf = cmdbuf + "  T3.[CIvDsc] AS EntCIvDsc, T1.[EntFpa], T1.[EntEMa], T1.[EntFax], T1.[EntTel], T1.[EntDom], "
      cmdbuf = cmdbuf + "  T1.[EntPos], T2.[paidsc] AS EntPaiDsc, T1.[EntCont] FROM (([ENTID] T1 (NOLOCK) LEFT "
      cmdbuf = cmdbuf + "  JOIN [paises] T2 (NOLOCK) ON T2.[paicod] = T1.[EntPaiCod]) LEFT JOIN [CATIVA] T3 "
      cmdbuf = cmdbuf + "  (NOLOCK) ON T3.[CIvCod] = T1.[EntCIvCod]) WHERE (T1.[EmpCod] = ? and T1.[EntGruTip] "
      cmdbuf = cmdbuf + "  = ? and T1.[EntCod] >= ?) AND (T1.[EntInhab] = ? or ? = 'T' or ( T1.[EntInhab] = "
      cmdbuf = cmdbuf + "  ' ' and ? <> 'S')) AND (T1.[EntCod] <= ?) ORDER BY T1.[EmpCod], T1.[EntGruTip], "
      cmdbuf = cmdbuf + "  T1.[EntCod]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04602,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R04602,100)
      GX_DB_BindColsR04602_01 ()
      GX_DB_BindParmR04602_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_R04602,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetStr( HStmt_R04602,2,RV38Entgru,2,0)
   Gx_err = GX_DB_SetLong( HStmt_R04602,3,@AV11Despro,0)
   Gx_err = GX_DB_SetStr( HStmt_R04602,4,AV41Entinh,1,0)
   Gx_err = GX_DB_SetStr( HStmt_R04602,5,AV41Entinh,1,0)
   Gx_err = GX_DB_SetStr( HStmt_R04602,6,AV41Entinh,1,0)
   Gx_err = GX_DB_SetLong( HStmt_R04602,7,@AV12Haspro,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04602) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R04602 = Gx_err
   GX_DB_GetR04602_01 ()
   DO WHILE R04602 <> 101
      R157EntPai = Buf_R04602_157EntPaiCod
      R2EmpCod = Buf_R04602_2EmpCod
      R150EntGru = Buf_R04602_150EntGruTip
      R120EntCod = Buf_R04602_120EntCod
      R1717EntIn = Buf_R04602_1717EntInhab
      R153EntRaz = Buf_R04602_153EntRaz
      R1475EntPI = Buf_R04602_1475EntPIBFR
      R1469CtaCl = Buf_R04602_1469CtaCliCod
      R1267Enttd = Buf_R04602_1267Enttd
      R175EntFVt = Buf_R04602_175EntFVt
      R166EntCui = Buf_R04602_166EntCui
      R171EntCIv = Buf_R04602_171EntCIvCod
      R159EntPci = Buf_R04602_159EntPciCod
      R161EntMun = Buf_R04602_161EntMunCod
      R1685EntCr = Buf_R04602_1685EntCred
      R174EntDes = Buf_R04602_174EntDesc
      R172EntCIv = Buf_R04602_172EntCIvDsc
      R168EntFpa = Buf_R04602_168EntFpa
      R167EntEMa = Buf_R04602_167EntEMa
      R165EntFax = Buf_R04602_165EntFax
      R164EntTel = Buf_R04602_164EntTel
      R156EntDom = Buf_R04602_156EntDom
      R163EntPos = Buf_R04602_163EntPos
      R158EntPai = Buf_R04602_158EntPaiDsc
      R155EntCon = Buf_R04602_155EntCont
      R158EntPai = Buf_R04602_158EntPaiDsc
      R172EntCIv = Buf_R04602_172EntCIvDsc
      IF ( R171EntCIv = AV13Entciv .OR. AV13Entciv = 88 ) .AND. ( R166EntCui = AV14Entcui .OR. AV14Entcui = 0 ) .AND. ( R175EntFVt = AV15Entfvt .OR. AV15Entfvt = "TT" ) .AND. ( R1267Enttd = AV16Enttd .OR. AV16Enttd = "T" ) .AND. ( R1469CtaCl = AV17Ctacli .OR. AV17Ctacli = 0 ) .AND. ( R1475EntPI = AV18Entpib .OR. AV18Entpib = "T" )
         RV39Entcod = R120EntCod
         IF AV37Ultima <> CTOD("  /  /  ")
            RV40Ok = 1
         ELSE
            RV40Ok = 0
            GX_retp = 0
            DO U11CS3
            IF GX_retp = 1
               RETURN
            ENDIF
         ENDIF
         IF RV40Ok = 1
            RV22Primer = "S"
            DO CASE
               CASE R175EntFVt = "FF"
                  RV24Formav = "Factura"
               CASE R175EntFVt = "FR"
                  RV24Formav = "Fac/Rto"
               CASE R175EntFVt = "RF"
                  RV24Formav = "Remito"
            ENDCASE
            DO CASE
               CASE R1267Enttd = "N"
                  RV25Tipode = "Normal"
               CASE R1267Enttd = "I"
                  RV25Tipode = "Incob."
               CASE R1267Enttd = "G"
                  RV25Tipode = "Gest.Jud."
               CASE R1267Enttd = "C"
                  RV25Tipode = "Conc/Qbra"
            ENDCASE
            DO GX_MSGW WITH "Cliente :" + str( R120EntCod , 6 ) + " " + R153EntRaz
            IF AV23Porsuc <> "S"
               RV31Pcicod = R159EntPci
               RV35Muncod = R161EntMun
               GX_retp = 0
               DO U12CS3
               IF GX_retp = 1
                  RETURN
               ENDIF
               DO HCS0 WITH Gx_out , P_lines , Gx_line , 0 , .F., 80
               gxPrnObj.GxDwText( GxHDC , TRANSFORM(R120EntCod, "999999")  ,16,8+Gx_line,45,23+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwText( GxHDC , R153EntRaz ,56,8+Gx_line,215,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwText( GxHDC , R155EntCon ,360,8+Gx_line,519,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Contacto ] ,320,8+Gx_line,359,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , R158EntPai ,936,8+Gx_line,1095,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwText( GxHDC , R163EntPos ,696,32+Gx_line,735,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Cod. Pos.] ,648,32+Gx_line,691,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , R156EntDom ,576,8+Gx_line,735,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Domicilio ] ,528,8+Gx_line,568,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , RV33Mundsc ,816,32+Gx_line,1095,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwText( GxHDC , R164EntTel ,56,32+Gx_line,215,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Tel.] ,31,32+Gx_line,45,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , R165EntFax ,280,32+Gx_line,439,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Fax] ,240,32+Gx_line,256,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , R167EntEMa ,472,32+Gx_line,631,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Mail] ,448,32+Gx_line,465,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwTextNB( GxHDC , [Munic.] ,779,32+Gx_line,807,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , TRANSFORM(R166EntCui, "@L 99-99999999-9")  ,56,56+Gx_line,120,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [C.U.I.T. ] ,16,56+Gx_line,54,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , TRANSFORM(R168EntFpa, "999")  ,496,56+Gx_line,510,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Cobros a ] ,448,56+Gx_line,489,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwTextNB( GxHDC , [dias F.F.] ,512,56+Gx_line,549,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , R172EntCIv ,280,56+Gx_line,439,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Cat. IVA] ,240,56+Gx_line,277,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , TRANSFORM(R174EntDes, "999.99")  ,602,56+Gx_line,631,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [% desc.] ,560,56+Gx_line,596,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , RV24Formav ,696,56+Gx_line,758,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Forma Vta.] ,648,56+Gx_line,694,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwTextNB( GxHDC , [Tpo Deuda ] ,779,56+Gx_line,826,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , RV25Tipode ,840,56+Gx_line,920,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwText( GxHDC , R1475EntPI ,992,56+Gx_line,1000,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Perc. IIBB x] ,936,56+Gx_line,990,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwTextNB( GxHDC , [Cta. Cte.] ,240,8+Gx_line,278,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , TRANSFORM(R1469CtaCl, "999999")  ,280,8+Gx_line,309,23+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwText( GxHDC , TRANSFORM(R1685EntCr, "999999999.99")  ,1044,56+Gx_line,1103,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               gxPrnObj.GxDwTextNB( GxHDC , [Crédito ] ,1008,56+Gx_line,1040,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
               gxPrnObj.GXDwLine( GxHDC ,8,0+Gx_line,1096,0+Gx_line ,1 ,0,0,0 )
               gxPrnObj.GxDwText( GxHDC , RV32Pcidsc ,760,8+Gx_line,919,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
               Gx_line = Gx_line + 80
            ELSE
               GX_retp = 0
               DO U13CS3
               IF GX_retp = 1
                  RETURN
               ENDIF
            ENDIF
         ENDIF
      ENDIF
      * Check if program is canceled.
      IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
         UserCancel = .T.
      ENDIF
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R04602) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R04602 = Gx_err
      GX_DB_GetR04602_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04602) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL3 = .F.
   IF AV17Ctacli > 0
      RV26Txt = "#Cltes " + str( AV11Despro , 6 ) + " - " + str( AV12Haspro , 6 ) + " #C.U.I.T. " + str( AV14Entcui , 11 ) + " #Cta. Cte. " + str( AV17Ctacli , 6 )
   ELSE
      RV26Txt = "#Cltes " + str( AV11Despro , 6 ) + " - " + str( AV12Haspro , 6 ) + " #C.U.I.T. " + str( AV14Entcui , 11 )
   ENDIF
   DO CASE
      CASE AV16Enttd = "N"
         RV25Tipode = "#Tipo Deuda = Normal"
      CASE AV16Enttd = "I"
         RV25Tipode = "#Tipo Deuda = Incob."
      CASE AV16Enttd = "G"
         RV25Tipode = "#Tipo Deuda = Gest.Jud."
      CASE AV16Enttd = "C"
         RV25Tipode = "#Tipo Deuda = Conc/Qbra"
      OTHERWISE
         RV25Tipode = " "
   ENDCASE
   RV26Txt = RV26Txt + ALLTRIM( RV25Tipode )
   DO CASE
      CASE AV15Entfvt = "FF"
         RV24Formav = " #Tipo Vta = Factura"
      CASE R175EntFVt = "FR"
         RV24Formav = " #Tipo Vta = Fac/Rto"
      CASE R175EntFVt = "RF"
         RV24Formav = " #Tipo Vta = Remito"
      OTHERWISE
         RV24Formav = " "
   ENDCASE
   RV26Txt = RV26Txt + ALLTRIM( RV24Formav )
   IF AV13Entciv <> 88
      LEVEL4 = .T.
      DO GX_CSC01
      IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04603" , @HStmt_R04603 )
         Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04603","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_R04603) ,  ,  ,  , CS_SQLSRV ,  )
         cmdbuf = " SELECT [CIvCod], [CIvDsc] FROM [CATIVA] (NOLOCK) WHERE [CIvCod] = ? ORDER BY [CIvCod] "
         cmdbuf = cmdbuf + "   "
         Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04603,cmdbuf)
         GX_DB_BindColsR04603_01 ()
         GX_DB_BindParmR04603_01 ()
      ENDIF
      Gx_err = GX_DB_SetInt( HStmt_R04603,1,@AV13Entciv,0)
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04603) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R04603 = Gx_err
      GX_DB_GetR04603_01 ()
      DO WHILE R04603 <> 101
         R88CIvCod = Buf_R04603_88CIvCod
         R89CIvDsc = Buf_R04603_89CIvDsc
         RV26Txt = RV26Txt + " #Cat. IVA = " + R89CIvDsc
         * Check if program is canceled.
         IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
            UserCancel = .T.
         ENDIF
         DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
         IF UserCancel
            EXIT
         ENDIF
         * Exiting from a For First loop.
         EXIT
         IF UserCancel
            EXIT
         ENDIF
      ENDDO
      Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04603) ,  ,  ,  , CS_SQLSRV ,  )
      LEVEL4 = .F.
   ENDIF
   DO CASE
      CASE AV18Entpib = "F"
         RV26Txt = RV26Txt + " #Perc. IIBB x Factura"
      CASE AV18Entpib = "R"
         RV26Txt = RV26Txt + " #Perc. IIBB x Remito"
   ENDCASE
   IF AV23Porsuc = "S"
      RV27Txt1 = "Sucursales :"
      IF AV19Entlgc <> 88
         LEVEL5 = .T.
         DO GX_CSC01
         IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04604" , @HStmt_R04604 )
            Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04604","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_R04604) ,  ,  ,  , CS_SQLSRV ,  )
            cmdbuf = " SELECT [CIvCod], [CIvDsc] FROM [CATIVA] (NOLOCK) WHERE [CIvCod] = ? ORDER BY [CIvCod] "
            cmdbuf = cmdbuf + "   "
            Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04604,cmdbuf)
            GX_DB_BindColsR04604_01 ()
            GX_DB_BindParmR04604_01 ()
         ENDIF
         Gx_err = GX_DB_SetInt( HStmt_R04604,1,@AV19Entlgc,0)
         Gx_eop = 1
         DO WHILE Gx_eop != 0
            Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04604) ,  ,  ,  , CS_SQLSRV ,  )
         ENDDO
         R04604 = Gx_err
         GX_DB_GetR04604_01 ()
         DO WHILE R04604 <> 101
            R88CIvCod = Buf_R04604_88CIvCod
            R89CIvDsc = Buf_R04604_89CIvDsc
            RV26Txt = RV26Txt + " #Cat. IVA Suc. = " + R89CIvDsc
            * Check if program is canceled.
            IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
               UserCancel = .T.
            ENDIF
            DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
            IF UserCancel
               EXIT
            ENDIF
            * Exiting from a For First loop.
            EXIT
            IF UserCancel
               EXIT
            ENDIF
         ENDDO
         Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04604) ,  ,  ,  , CS_SQLSRV ,  )
         LEVEL5 = .F.
      ENDIF
      IF AV21Entlgv <> 8888
         LEVEL6 = .T.
         DO GX_CSC01
         IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04605" , @HStmt_R04605 )
            Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04605","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_R04605) ,  ,  ,  , CS_SQLSRV ,  )
            cmdbuf = " SELECT [EmpCod], [VdrCod], [VdrNom] FROM [VEND] (NOLOCK) WHERE [EmpCod] = ? and [VdrCod] "
            cmdbuf = cmdbuf + "  = ? ORDER BY [EmpCod], [VdrCod]  "
            Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04605,cmdbuf)
            GX_DB_BindColsR04605_01 ()
            GX_DB_BindParmR04605_01 ()
         ENDIF
         Gx_err = GX_DB_SetInt( HStmt_R04605,1,@AV8Emprcod,0)
         Gx_err = GX_DB_SetInt( HStmt_R04605,2,@AV21Entlgv,0)
         Gx_eop = 1
         DO WHILE Gx_eop != 0
            Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04605) ,  ,  ,  , CS_SQLSRV ,  )
         ENDDO
         R04605 = Gx_err
         GX_DB_GetR04605_01 ()
         DO WHILE R04605 <> 101
            R2EmpCod = Buf_R04605_2EmpCod
            R1037VdrCo = Buf_R04605_1037VdrCod
            R1038VdrNo = Buf_R04605_1038VdrNom
            RV26Txt = RV26Txt + " #Vendedor Suc. " + R1038VdrNo
            * Check if program is canceled.
            IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
               UserCancel = .T.
            ENDIF
            DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
            IF UserCancel
               EXIT
            ENDIF
            * Exiting from a For First loop.
            EXIT
            IF UserCancel
               EXIT
            ENDIF
         ENDDO
         Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04605) ,  ,  ,  , CS_SQLSRV ,  )
         LEVEL6 = .F.
      ENDIF
      DO CASE
         CASE AV20Entlgf = "FF"
            RV24Formav = " #Tipo Vta Suc. = Factura"
         CASE AV20Entlgf = "FR"
            RV24Formav = " #Tipo Vta Suc. = Fac/Rto"
         CASE AV20Entlgf = "RF"
            RV24Formav = " #Tipo Vta Suc. = Remito"
         OTHERWISE
            RV24Formav = " "
      ENDCASE
      RV27Txt1 = RV27Txt1 + ALLTRIM( RV24Formav )
   ELSE
      RV27Txt1 = SPACE(250)
   ENDIF
   DO HCS0 WITH Gx_out , P_lines , Gx_line , 0 , .F., 120
   gxPrnObj.GxDwTextNB( GxHDC , [Opciones ] ,16,24+Gx_line,58,39+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
   gxPrnObj.GxDwText( GxHDC , RV26Txt ,24,40+Gx_line,1023,55+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
   gxPrnObj.GxDwText( GxHDC , RV27Txt1 ,24,64+Gx_line,1023,79+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
   Gx_line = Gx_line + 120
   DO EPCS0
   DO ReleaseReport IN GXForm.prg
   RETURN
   GX_retp = 0
* End Program

***********************
PROCEDURE EPCS0
***********************

   DO HCS0 WITH Gx_out , P_lines , 0, P_lines +1, .T., 0
   IF Gx_dvc = "PRN"
      GXAuxPrn_Flag = GXPrn_Flag
      gxPrnObj.GXEndDoc( GxHDC , @GXAuxPrn_Flag)
      gxPrnObj.GXEndPrn( GxHDC , @GXAuxPrn_Flag)
      GXPrn_Flag = GXAuxPrn_Flag
      PRIVATE GXCallFrm
      IF PROGRAM(0) = "MENU"
         GXCallFrm = _SCREEN.ActiveForm
         IF ! ISNULL(GXCallFrm)
            GXCallFrm.Enabled = 0
         ENDIF
      ENDIF
      DO WHILE gxPrnObj.GxIsAliveDoc( GxHDC ) != 0
         WAIT "" TIMEOUT 1
         DOEVENTS
      ENDDO
      RELEASE WINDOW _WMSG
      IF PROGRAM(0) = "MENU"
         IF ! ISNULL(GXCallFrm)
            GXCallFrm.Enabled = 1
         ENDIF
      ENDIF
   ELSE
      SET DEVICE TO SCREEN
      RptView = .T.
   ENDIF
   DO CDCS0
   IF WEXIST( GX_newwin )
      RELEASE WINDOW (GX_newwin)
      IF !EMPTY( LastWin )
         ACTIVATE WINDOW (LastWin)
         MODIFY WINDOW (LastWin) CLOSE
      ENDIF
   ENDIF
RETURN

***********************
PROCEDURE U13CS3
***********************

   * 'SUCURSAL' Routine
   LEVEL7 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04606" , @HStmt_R04606 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04606","",GX_CURSOR_TYPE_READONLY,@HStmt_R04606) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT T2.[EntPaiCod] AS EntPaiCod, T2.[EntCIvCod] AS EntCIvCod, T1.[EmpCod], T1.[EntCod], "
      cmdbuf = cmdbuf + "  T1.[EntGruTip], T1.[EntLgFVt], T1.[EntLgVdrCo] AS EntLgVdrCo, T1.[EntLgCIvCo] AS "
      cmdbuf = cmdbuf + "  EntLgCIvCo, T2.[EntPciCod], T2.[EntMunCod], T2.[EntDes1], T2.[EntCPIB], T2.[CtaCliCod], "
      cmdbuf = cmdbuf + "  T4.[CIvDsc] AS EntCIvDsc, T2.[EntCui], T2.[EntFax], T2.[EntTel], T2.[EntRaz], T2.[EntCred], "
      cmdbuf = cmdbuf + "  T2.[EntPIBFR], T2.[EntDesc], T2.[EntFpa], T2.[EntEMa], T2.[EntDom], T2.[EntPos], "
      cmdbuf = cmdbuf + "  T3.[paidsc] AS EntPaiDsc, T2.[EntCont], T1.[EntLgPciCo], T1.[EntLgMunCo], T1.[EntLgIBRet], "
      cmdbuf = cmdbuf + "  T1.[EntLgOrden], T6.[CIvDsc] AS EntLgCIvDs, T5.[VdrNom] AS EntLgVdrNo, T1.[EntLgTel], "
      cmdbuf = cmdbuf + "  T1.[Entlgloc], T1.[EntLgCont], T1.[EntLgDom], T1.[EntLgCod] FROM ((((([CLTES] T1 "
      cmdbuf = cmdbuf + "  (NOLOCK) LEFT JOIN [ENTID] T2 (NOLOCK) ON T2.[EmpCod] = T1.[EmpCod] AND T2.[EntGruTip] "
      cmdbuf = cmdbuf + "  = T1.[EntGruTip] AND T2.[EntCod] = T1.[EntCod]) LEFT JOIN [paises] T3 (NOLOCK) ON "
      cmdbuf = cmdbuf + "  T3.[paicod] = T2.[EntPaiCod]) LEFT JOIN [CATIVA] T4 (NOLOCK) ON T4.[CIvCod] = T2.[EntCIvCod]) "
      cmdbuf = cmdbuf + "  LEFT JOIN [VEND] T5 (NOLOCK) ON T5.[EmpCod] = T1.[EmpCod] AND T5.[VdrCod] = T1.[EntLgVdrCo]) "
      cmdbuf = cmdbuf + "  LEFT JOIN [CATIVA] T6 (NOLOCK) ON T6.[CIvCod] = T1.[EntLgCIvCo]) WHERE (T1.[EmpCod] "
      cmdbuf = cmdbuf + "  = ? and T1.[EntGruTip] = ? and T1.[EntCod] = ?) AND (T1.[EntLgFVt] = ? or ? = 'TT') "
      cmdbuf = cmdbuf + "  AND (T1.[EntLgVdrCo] = ? or ? = 8888) AND (T1.[EntLgCIvCo] = ? or ? = 88) ORDER "
      cmdbuf = cmdbuf + "  BY T1.[EmpCod], T1.[EntGruTip], T1.[EntCod], T1.[EntLgCod]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04606,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R04606,100)
      GX_DB_BindColsR04606_01 ()
      GX_DB_BindParmR04606_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_R04606,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetStr( HStmt_R04606,2,RV38Entgru,2,0)
   Gx_err = GX_DB_SetLong( HStmt_R04606,3,@RV39Entcod,0)
   Gx_err = GX_DB_SetStr( HStmt_R04606,4,AV20Entlgf,2,0)
   Gx_err = GX_DB_SetStr( HStmt_R04606,5,AV20Entlgf,2,0)
   Gx_err = GX_DB_SetInt( HStmt_R04606,6,@AV21Entlgv,0)
   Gx_err = GX_DB_SetInt( HStmt_R04606,7,@AV21Entlgv,0)
   Gx_err = GX_DB_SetInt( HStmt_R04606,8,@AV19Entlgc,0)
   Gx_err = GX_DB_SetInt( HStmt_R04606,9,@AV19Entlgc,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04606) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R04606 = Gx_err
   GX_DB_GetR04606_01 ()
   DO WHILE R04606 <> 101
      R157EntPai = Buf_R04606_157EntPaiCod
      R171EntCIv = Buf_R04606_171EntCIvCod
      R2EmpCod = Buf_R04606_2EmpCod
      R120EntCod = Buf_R04606_120EntCod
      R150EntGru = Buf_R04606_150EntGruTip
      R187EntLgF = Buf_R04606_187EntLgFVt
      R188EntLgV = Buf_R04606_188EntLgVdrCo
      R1334EntLg = Buf_R04606_1334EntLgCIvCo
      R159EntPci = Buf_R04606_159EntPciCod
      R161EntMun = Buf_R04606_161EntMunCod
      R3270EntDe = Buf_R04606_3270EntDes1
      R2078EntCP = Buf_R04606_2078EntCPIB
      R1469CtaCl = Buf_R04606_1469CtaCliCod
      R172EntCIv = Buf_R04606_172EntCIvDsc
      R166EntCui = Buf_R04606_166EntCui
      R165EntFax = Buf_R04606_165EntFax
      R164EntTel = Buf_R04606_164EntTel
      R153EntRaz = Buf_R04606_153EntRaz
      R1685EntCr = Buf_R04606_1685EntCred
      R1475EntPI = Buf_R04606_1475EntPIBFR
      R174EntDes = Buf_R04606_174EntDesc
      R168EntFpa = Buf_R04606_168EntFpa
      R167EntEMa = Buf_R04606_167EntEMa
      R156EntDom = Buf_R04606_156EntDom
      R163EntPos = Buf_R04606_163EntPos
      R158EntPai = Buf_R04606_158EntPaiDsc
      R155EntCon = Buf_R04606_155EntCont
      R180EntLgP = Buf_R04606_180EntLgPciCo
      R182EntLgM = Buf_R04606_182EntLgMunCo
      R1439EntLg = Buf_R04606_1439EntLgIBRet
      R192EntLgO = Buf_R04606_192EntLgOrden
      R1335EntLg = Buf_R04606_1335EntLgCIvDs
      R189EntLgV = Buf_R04606_189EntLgVdrNo
      R186EntLgT = Buf_R04606_186EntLgTel
      R1076Entlg = Buf_R04606_1076Entlgloc
      R185EntLgC = Buf_R04606_185EntLgCont
      R178EntLgD = Buf_R04606_178EntLgDom
      R176EntLgC = Buf_R04606_176EntLgCod
      R157EntPai = Buf_R04606_157EntPaiCod
      R171EntCIv = Buf_R04606_171EntCIvCod
      R159EntPci = Buf_R04606_159EntPciCod
      R161EntMun = Buf_R04606_161EntMunCod
      R3270EntDe = Buf_R04606_3270EntDes1
      R2078EntCP = Buf_R04606_2078EntCPIB
      R1469CtaCl = Buf_R04606_1469CtaCliCod
      R166EntCui = Buf_R04606_166EntCui
      R165EntFax = Buf_R04606_165EntFax
      R164EntTel = Buf_R04606_164EntTel
      R153EntRaz = Buf_R04606_153EntRaz
      R1685EntCr = Buf_R04606_1685EntCred
      R1475EntPI = Buf_R04606_1475EntPIBFR
      R174EntDes = Buf_R04606_174EntDesc
      R168EntFpa = Buf_R04606_168EntFpa
      R167EntEMa = Buf_R04606_167EntEMa
      R156EntDom = Buf_R04606_156EntDom
      R163EntPos = Buf_R04606_163EntPos
      R155EntCon = Buf_R04606_155EntCont
      R158EntPai = Buf_R04606_158EntPaiDsc
      R172EntCIv = Buf_R04606_172EntCIvDsc
      R189EntLgV = Buf_R04606_189EntLgVdrNo
      R1335EntLg = Buf_R04606_1335EntLgCIvDs
      RV31Pcicod = R159EntPci
      RV35Muncod = R161EntMun
      GX_retp = 0
      DO U12CS3
      IF GX_retp = 1
         RETURN
      ENDIF
      IF RV22Primer = "S"
         DO HCS0 WITH Gx_out , P_lines , Gx_line , 0 , .F., 80
         gxPrnObj.GXDwLine( GxHDC ,8,0+Gx_line,1096,0+Gx_line ,2 ,0,0,0 )
         gxPrnObj.GxDwTextNB( GxHDC , [Mail] ,448,32+Gx_line,465,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , R155EntCon ,360,8+Gx_line,519,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , R158EntPai ,936,8+Gx_line,1095,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , R163EntPos ,696,32+Gx_line,735,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Cod. Pos.] ,648,32+Gx_line,691,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , R156EntDom ,576,8+Gx_line,735,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Domicilio ] ,528,8+Gx_line,568,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , R167EntEMa ,472,32+Gx_line,631,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Munic.] ,779,32+Gx_line,807,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R168EntFpa, "999")  ,384,56+Gx_line,398,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Cobros a ] ,336,56+Gx_line,377,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwTextNB( GxHDC , [dias F.F.] ,400,56+Gx_line,437,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R174EntDes, "999.99")  ,490,56+Gx_line,519,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [% desc.] ,448,56+Gx_line,484,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , RV24Formav ,600,56+Gx_line,662,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [F. Vta.] ,568,56+Gx_line,596,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwTextNB( GxHDC , [Tpo Deuda ] ,667,56+Gx_line,714,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , RV25Tipode ,728,56+Gx_line,808,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , R1475EntPI ,880,56+Gx_line,888,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Perc. IIBB x] ,824,56+Gx_line,878,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R1685EntCr, "999999999.99")  ,1044,56+Gx_line,1103,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Crédito ] ,1008,56+Gx_line,1040,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R120EntCod, "999999")  ,16,8+Gx_line,45,23+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , R153EntRaz ,48,8+Gx_line,207,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Contacto ] ,320,8+Gx_line,359,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , R164EntTel ,56,32+Gx_line,215,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Tel.] ,31,32+Gx_line,45,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , R165EntFax ,280,32+Gx_line,439,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Fax] ,240,32+Gx_line,256,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R166EntCui, "@L 99-99999999-9")  ,56,56+Gx_line,120,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [C.U.I.T. ] ,16,56+Gx_line,54,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , R172EntCIv ,168,56+Gx_line,327,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Cat. IVA] ,128,56+Gx_line,165,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwTextNB( GxHDC , [Cta. Cte.] ,240,8+Gx_line,278,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R1469CtaCl, "999999")  ,280,8+Gx_line,309,23+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , RV32Pcidsc ,752,8+Gx_line,911,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , RV33Mundsc ,808,32+Gx_line,1087,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwTextNB( GxHDC , [Coef. Perc IIBB ] ,896,56+Gx_line,967,71+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R2078EntCP, "99.99")  ,968,56+Gx_line,992,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(R3270EntDe, "999.99")  ,528,56+Gx_line,557,71+Gx_line , "Arial Narrow",9 ,258 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         Gx_line = Gx_line + 80
         RV22Primer = "N"
      ENDIF
      DO CASE
         CASE R187EntLgF = "FF"
            RV24Formav = "Factura"
         CASE R187EntLgF = "FR"
            RV24Formav = "Fac/Rto"
         CASE R187EntLgF = "RF"
            RV24Formav = "Remito"
      ENDCASE
      RV31Pcicod = R180EntLgP
      RV35Muncod = R182EntLgM
      GX_retp = 0
      DO U12CS3
      IF GX_retp = 1
         RETURN
      ENDIF
      DO HCS0 WITH Gx_out , P_lines , Gx_line , 0 , .F., 56
      gxPrnObj.GXDwLine( GxHDC ,15,0+Gx_line,1103,0+Gx_line ,1 ,0,0,0 )
      gxPrnObj.GxDwText( GxHDC , TRANSFORM(R176EntLgC, "9999")  ,39,8+Gx_line,58,23+Gx_line , "Arial Narrow",9 ,258 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwText( GxHDC , R178EntLgD ,64,8+Gx_line,223,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwText( GxHDC , RV32Pcidsc ,288,8+Gx_line,447,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwText( GxHDC , R185EntLgC ,936,8+Gx_line,1095,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwTextNB( GxHDC , [Contacto ] ,888,8+Gx_line,927,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwText( GxHDC , R1076Entlg ,744,8+Gx_line,823,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwText( GxHDC , R186EntLgT ,86,32+Gx_line,245,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwTextNB( GxHDC , [Tel.] ,61,32+Gx_line,75,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwTextNB( GxHDC , [Forma Vta.] ,768,32+Gx_line,814,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwText( GxHDC , RV24Formav ,816,32+Gx_line,878,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwText( GxHDC , R189EntLgV ,576,32+Gx_line,735,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwTextNB( GxHDC , [Vendedor ] ,528,32+Gx_line,570,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwText( GxHDC , R1335EntLg ,288,32+Gx_line,447,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwText( GxHDC , R192EntLgO ,936,32+Gx_line,1095,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwTextNB( GxHDC , [Nro. Orden] ,883,32+Gx_line,930,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwTextNB( GxHDC , [Ret. IIBB] ,456,32+Gx_line,495,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwText( GxHDC , R1439EntLg ,504,32+Gx_line,512,47+Gx_line , "Arial Narrow",9 ,256 ,0,0,1,0 ,0 ,0,0,0 , 1, 255,255,255 )
      gxPrnObj.GxDwTextNB( GxHDC , [Suc. ] ,16,8+Gx_line,38,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwTextNB( GxHDC , [-] ,57,8+Gx_line,59,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 )
      gxPrnObj.GxDwText( GxHDC , RV33Mundsc ,456,8+Gx_line,735,23+Gx_line , "Arial Narrow",9 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
      Gx_line = Gx_line + 56
      * Check if program is canceled.
      IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
         UserCancel = .T.
      ENDIF
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R04606) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R04606 = Gx_err
      GX_DB_GetR04606_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04606) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL7 = .F.
RETURN

***********************
PROCEDURE U12CS3
***********************

   * 'XMUNI' Routine
   LEVEL8 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04607" , @HStmt_R04607 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04607","",GX_CURSOR_TYPE_READONLY_NOTNESTED,@HStmt_R04607) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [paicod], [pcicod], [muncod], [munaba], [mundsc], [MunTap], [MunRell], [MunNRell], "
      cmdbuf = cmdbuf + "  [MunMin], [MunHue], [MunCar], [MunRic], [MunAliH], [MunAliC], [MunAliR] FROM [muni] "
      cmdbuf = cmdbuf + "  (NOLOCK) WHERE ([paicod] = '54  ') AND ([pcicod] = ?) AND ([muncod] = ?)  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04607,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R04607,100)
      GX_DB_BindColsR04607_01 ()
      GX_DB_BindParmR04607_01 ()
   ENDIF
   Gx_err = GX_DB_SetStr( HStmt_R04607,1,RV31Pcicod,4,0)
   Gx_err = GX_DB_SetStr( HStmt_R04607,2,RV35Muncod,4,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04607) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R04607 = Gx_err
   GX_DB_GetR04607_01 ()
   DO WHILE R04607 <> 101
      R2080xPaiC = Buf_R04607_2080xPaiCod
      R2081xPciC = Buf_R04607_2081xPciCod
      R2082xMunC = Buf_R04607_2082xMunCod
      R2083xMunA = Buf_R04607_2083xMunAba
      R2084xMunD = Buf_R04607_2084xMunDsc
      R2085xMunT = Buf_R04607_2085xMunTap
      R2086xMunR = Buf_R04607_2086xMunRell
      R2087xMunN = Buf_R04607_2087xMunNRell
      R2088xMunM = Buf_R04607_2088xMunMin
      R2089xMunH = Buf_R04607_2089xMunHue
      R2090xMunC = Buf_R04607_2090xMunCar
      R2091xMunR = Buf_R04607_2091xMunRic
      R2092xMunA = Buf_R04607_2092xMunAliH
      R2093xMunA = Buf_R04607_2093xMunAlic
      R2094xMunA = Buf_R04607_2094xMunAlir
      RV33Mundsc = R2084xMunD
      RV36Munaba = R2083xMunA
      * Check if program is canceled.
      IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
         UserCancel = .T.
      ENDIF
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R04607) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R04607 = Gx_err
      GX_DB_GetR04607_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04607) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL8 = .F.
   LEVEL9 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04608" , @HStmt_R04608 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04608","",GX_CURSOR_TYPE_READONLY_NOTNESTED,@HStmt_R04608) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [PaiCod], [PciCod], [PciDsc], [PciIbr], [PciDGI], [PciCou], [PciCo2], [pciibb], "
      cmdbuf = cmdbuf + "  [pciibA], [pciagp], [pciagr] FROM [Pcias] (NOLOCK) WHERE ([PaiCod] = '54  ') AND "
      cmdbuf = cmdbuf + "  ([PciCod] = ?)  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04608,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R04608,100)
      GX_DB_BindColsR04608_01 ()
      GX_DB_BindParmR04608_01 ()
   ENDIF
   Gx_err = GX_DB_SetStr( HStmt_R04608,1,RV31Pcicod,4,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04608) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R04608 = Gx_err
   GX_DB_GetR04608_01 ()
   DO WHILE R04608 <> 101
      R2080xPaiC = Buf_R04608_2080xPaiCod
      R2081xPciC = Buf_R04608_2081xPciCod
      R2096xPciD = Buf_R04608_2096xPciDsc
      R2097xPciI = Buf_R04608_2097xPciIbr
      R2098xPcID = Buf_R04608_2098xPcIDGI
      R2099xPciC = Buf_R04608_2099xPciCoU
      R2100xPciC = Buf_R04608_2100xPciCo2
      R2243xPciI = Buf_R04608_2243xPciIbB
      R3096xPciI = Buf_R04608_3096xPciIbA
      R3425xPciA = Buf_R04608_3425xPciAgP
      R3426xPciA = Buf_R04608_3426xPciAgR
      RV32Pcidsc = R2096xPciD
      * Check if program is canceled.
      IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
         UserCancel = .T.
      ENDIF
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R04608) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R04608 = Gx_err
      GX_DB_GetR04608_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04608) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL9 = .F.
RETURN

***********************
PROCEDURE U11CS3
***********************

   * 'ULTIMA' Routine
   LEVEL10 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R04609" , @HStmt_R04609 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLCLTES","R04609","",GX_CURSOR_TYPE_READONLY_NOTNESTED,@HStmt_R04609) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [DcVNroInt], [DcVFch], [DcVEntCod], [EmpCod] FROM [DCVENT] (NOLOCK) WHERE "
      cmdbuf = cmdbuf + "  [EmpCod] = ? and [DcVEntCod] = ? and [DcVFch] >= ? ORDER BY [EmpCod], [DcVEntCod], "
      cmdbuf = cmdbuf + "  [DcVFch]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R04609,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R04609,100)
      GX_DB_BindColsR04609_01 ()
      GX_DB_BindParmR04609_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_R04609,1,@AV8Emprcod,0)
   Gx_err = GX_DB_SetLong( HStmt_R04609,2,@RV39Entcod,0)
   Gx_err = GX_DB_SetDate( HStmt_R04609,3,@AV37Ultima,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R04609) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R04609 = Gx_err
   GX_DB_GetR04609_01 ()
   DO WHILE R04609 <> 101
      R421DcVFch = Buf_R04609_421DcVFch
      R417DcVEnt = Buf_R04609_417DcVEntCod
      R2EmpCod = Buf_R04609_2EmpCod
      RV40Ok = 1
      * Exit For each command. Update data (if necessary), close cursors & exit.
      EXIT
      * Check if program is canceled.
      IF gxPrnObj.GxIsAliveDoc( GxHDC ) = 0
         UserCancel = .T.
      ENDIF
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R04609) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R04609 = Gx_err
      GX_DB_GetR04609_01 ()
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R04609) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL10 = .F.
RETURN

***********************
PROCEDURE HCS0
***********************

   PARAMETERS Gx_out, P_lines, Gx_line, Gx_inc, GX_footer, GX_inc_test

   Gx_line = Gx_line + Gx_inc
   IF Gx_line + GX_inc_test > P_lines
      IF Gx_page > 0
         Gx_line = P_lines
         IF Gx_dvc = "PRN" .and. Gx_pg_started
            GXAuxPrn_Flag = GXPrn_Flag
            gxPrnObj.GXEndPg( GxHDC , @GXAuxPrn_Flag)
            GXPrn_Flag = GXAuxPrn_Flag
            Gx_pg_started = .F.
         ENDIF
      ENDIF
      IF GX_footer
         RETURN
      ENDIF
      Gx_line = M_top
      Gx_page = Gx_page + 1
      IF Gx_dvc = "PRN" .and. .not. Gx_pg_started
         GXAuxPrn_Flag = GXPrn_Flag
         gxPrnObj.GXStartPg( GxHDC , @GXAuxPrn_Flag)
         GXPrn_Flag = GXAuxPrn_Flag
         Gx_pg_started = .T.
      ENDIF
      IF LEVEL1
         gxPrnObj.GxDwTextNB( GxHDC , [Listado de Clientes ] ,472,64+Gx_line,631,83+Gx_line , "MS Sans Serif",12 ,256 ,1,0,1,0 ,0 ,0,0,0 )
         gxPrnObj.GxDwText( GxHDC , AV10Usuari ,32,30+Gx_line,61,42+Gx_line , "Arial Narrow",7 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , RV29Emprno ,32,16+Gx_line,121,28+Gx_line , "Arial Narrow",7 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , TRANSFORM(Gx_page, "999999")  ,1056,24+Gx_line,1079,36+Gx_line , "Arial Narrow",7 ,258 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         SET CENTURY ON
         gxPrnObj.GxDwText( GxHDC , DTOC(AV9Fechasi) ,1044,39+Gx_line,1079,51+Gx_line , "Arial Narrow",7 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , Gx_time ,1024,53+Gx_line,1079,65+Gx_line , "Arial Narrow",7 ,256 ,0,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         gxPrnObj.GxDwText( GxHDC , RV42Titulo ,512,88+Gx_line,611,103+Gx_line , "Arial Narrow",9 ,257 ,1,0,0,0 ,0 ,0,0,0 , 1, 255,255,255 )
         Gx_line = Gx_line + 112
      ENDIF
   ENDIF
RETURN
PROCEDURE GX_DB_GetR04609_01
   Gx_err = GX_DB_GetColDouble( HStmt_R04609,1,@Buf_R04609_415DcVNroInt,0)
   Gx_err = GX_DB_GetColDate( HStmt_R04609,2,@Buf_R04609_421DcVFch,0)
   Gx_err = GX_DB_GetColLong( HStmt_R04609,3,@Buf_R04609_417DcVEntCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04609,4,@Buf_R04609_2EmpCod,0)
ENDPROC

PROCEDURE GX_DB_GetR04608_01
   Gx_err = GX_DB_GetColStr( HStmt_R04608,1,@Buf_R04608_2080xPaiCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04608,2,@Buf_R04608_2081xPciCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04608,3,@Buf_R04608_2096xPciDsc,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04608,4,@Buf_R04608_2097xPciIbr,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04608,5,@Buf_R04608_2098xPcIDGI,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04608,6,@Buf_R04608_2099xPciCoU,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04608,7,@Buf_R04608_2100xPciCo2,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04608,8,@Buf_R04608_2243xPciIbB,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04608,9,@Buf_R04608_3096xPciIbA,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04608,10,@Buf_R04608_3425xPciAgP,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04608,11,@Buf_R04608_3426xPciAgR,0)
ENDPROC

PROCEDURE GX_DB_GetR04607_01
   Gx_err = GX_DB_GetColStr( HStmt_R04607,1,@Buf_R04607_2080xPaiCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04607,2,@Buf_R04607_2081xPciCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04607,3,@Buf_R04607_2082xMunCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,4,@Buf_R04607_2083xMunAba,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04607,5,@Buf_R04607_2084xMunDsc,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,6,@Buf_R04607_2085xMunTap,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,7,@Buf_R04607_2086xMunRell,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,8,@Buf_R04607_2087xMunNRell,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,9,@Buf_R04607_2088xMunMin,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,10,@Buf_R04607_2089xMunHue,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,11,@Buf_R04607_2090xMunCar,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,12,@Buf_R04607_2091xMunRic,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,13,@Buf_R04607_2092xMunAliH,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,14,@Buf_R04607_2093xMunAlic,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04607,15,@Buf_R04607_2094xMunAlir,0)
ENDPROC

PROCEDURE GX_DB_GetR04606_01
   Gx_err = GX_DB_GetColStr( HStmt_R04606,1,@Buf_R04606_157EntPaiCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04606,2,@Buf_R04606_171EntCIvCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04606,3,@Buf_R04606_2EmpCod,0)
   Gx_err = GX_DB_GetColLong( HStmt_R04606,4,@Buf_R04606_120EntCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,5,@Buf_R04606_150EntGruTip,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,6,@Buf_R04606_187EntLgFVt,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04606,7,@Buf_R04606_188EntLgVdrCo,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04606,8,@Buf_R04606_1334EntLgCIvCo,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,9,@Buf_R04606_159EntPciCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,10,@Buf_R04606_161EntMunCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04606,11,@Buf_R04606_3270EntDes1,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04606,12,@Buf_R04606_2078EntCPIB,0)
   Gx_err = GX_DB_GetColLong( HStmt_R04606,13,@Buf_R04606_1469CtaCliCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,14,@Buf_R04606_172EntCIvDsc,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04606,15,@Buf_R04606_166EntCui,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,16,@Buf_R04606_165EntFax,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,17,@Buf_R04606_164EntTel,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,18,@Buf_R04606_153EntRaz,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04606,19,@Buf_R04606_1685EntCred,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,20,@Buf_R04606_1475EntPIBFR,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04606,21,@Buf_R04606_174EntDesc,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04606,22,@Buf_R04606_168EntFpa,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,23,@Buf_R04606_167EntEMa,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,24,@Buf_R04606_156EntDom,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,25,@Buf_R04606_163EntPos,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,26,@Buf_R04606_158EntPaiDsc,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,27,@Buf_R04606_155EntCont,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,28,@Buf_R04606_180EntLgPciCo,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,29,@Buf_R04606_182EntLgMunCo,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,30,@Buf_R04606_1439EntLgIBRet,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,31,@Buf_R04606_192EntLgOrden,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,32,@Buf_R04606_1335EntLgCIvDs,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,33,@Buf_R04606_189EntLgVdrNo,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,34,@Buf_R04606_186EntLgTel,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,35,@Buf_R04606_1076Entlgloc,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,36,@Buf_R04606_185EntLgCont,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04606,37,@Buf_R04606_178EntLgDom,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04606,38,@Buf_R04606_176EntLgCod,0)
ENDPROC

PROCEDURE GX_DB_GetR04605_01
   Gx_err = GX_DB_GetColInt( HStmt_R04605,1,@Buf_R04605_2EmpCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04605,2,@Buf_R04605_1037VdrCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04605,3,@Buf_R04605_1038VdrNom,0)
ENDPROC

PROCEDURE GX_DB_GetR04604_01
   Gx_err = GX_DB_GetColInt( HStmt_R04604,1,@Buf_R04604_88CIvCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04604,2,@Buf_R04604_89CIvDsc,0)
ENDPROC

PROCEDURE GX_DB_GetR04603_01
   Gx_err = GX_DB_GetColInt( HStmt_R04603,1,@Buf_R04603_88CIvCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04603,2,@Buf_R04603_89CIvDsc,0)
ENDPROC

PROCEDURE GX_DB_GetR04602_01
   Gx_err = GX_DB_GetColStr( HStmt_R04602,1,@Buf_R04602_157EntPaiCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04602,2,@Buf_R04602_2EmpCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,3,@Buf_R04602_150EntGruTip,0)
   Gx_err = GX_DB_GetColLong( HStmt_R04602,4,@Buf_R04602_120EntCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,5,@Buf_R04602_1717EntInhab,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,6,@Buf_R04602_153EntRaz,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,7,@Buf_R04602_1475EntPIBFR,0)
   Gx_err = GX_DB_GetColLong( HStmt_R04602,8,@Buf_R04602_1469CtaCliCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,9,@Buf_R04602_1267Enttd,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,10,@Buf_R04602_175EntFVt,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04602,11,@Buf_R04602_166EntCui,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04602,12,@Buf_R04602_171EntCIvCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,13,@Buf_R04602_159EntPciCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,14,@Buf_R04602_161EntMunCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04602,15,@Buf_R04602_1685EntCred,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R04602,16,@Buf_R04602_174EntDesc,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,17,@Buf_R04602_172EntCIvDsc,0)
   Gx_err = GX_DB_GetColInt( HStmt_R04602,18,@Buf_R04602_168EntFpa,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,19,@Buf_R04602_167EntEMa,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,20,@Buf_R04602_165EntFax,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,21,@Buf_R04602_164EntTel,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,22,@Buf_R04602_156EntDom,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,23,@Buf_R04602_163EntPos,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,24,@Buf_R04602_158EntPaiDsc,0)
   Gx_err = GX_DB_GetColStr( HStmt_R04602,25,@Buf_R04602_155EntCont,0)
ENDPROC

PROCEDURE GX_DB_BindColsR04609_01
   Gx_err = GX_DB_BindColDouble( HStmt_R04609,1,0)
   Gx_err = GX_DB_BindColDate( HStmt_R04609,2,0)
   Gx_err = GX_DB_BindColLong( HStmt_R04609,3,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04609,4,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04608_01
   Gx_err = GX_DB_BindColCharEx( HStmt_R04608,1,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04608,2,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04608,3,0,40,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04608,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04608,5,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04608,6,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04608,7,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04608,8,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04608,9,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04608,10,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04608,11,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04607_01
   Gx_err = GX_DB_BindColCharEx( HStmt_R04607,1,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04607,2,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04607,3,0,4,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04607,5,0,70,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,6,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,7,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,8,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,9,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,10,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,11,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,12,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,13,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,14,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04607,15,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04606_01
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,1,0,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04606,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04606,3,0)
   Gx_err = GX_DB_BindColLong( HStmt_R04606,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,5,0,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,6,0,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04606,7,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04606,8,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,9,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,10,0,4,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04606,11,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04606,12,0)
   Gx_err = GX_DB_BindColLong( HStmt_R04606,13,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,14,0,40,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04606,15,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,16,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,17,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,18,0,40,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04606,19,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,20,0,1,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04606,21,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04606,22,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,23,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,24,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,25,0,10,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,26,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,27,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,28,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,29,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,30,0,1,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,31,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,32,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,33,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,34,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,35,0,20,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,36,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04606,37,0,40,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04606,38,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04605_01
   Gx_err = GX_DB_BindColShort( HStmt_R04605,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04605,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04605,3,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04604_01
   Gx_err = GX_DB_BindColShort( HStmt_R04604,1,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04604,2,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04603_01
   Gx_err = GX_DB_BindColShort( HStmt_R04603,1,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04603,2,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindColsR04602_01
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,1,0,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04602,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,3,0,2,0)
   Gx_err = GX_DB_BindColLong( HStmt_R04602,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,5,0,1,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,6,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,7,0,1,0)
   Gx_err = GX_DB_BindColLong( HStmt_R04602,8,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,9,0,1,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,10,0,2,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04602,11,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04602,12,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,13,0,4,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,14,0,4,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04602,15,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R04602,16,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,17,0,40,0)
   Gx_err = GX_DB_BindColShort( HStmt_R04602,18,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,19,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,20,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,21,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,22,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,23,0,10,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,24,0,40,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R04602,25,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04609_01
   Gx_err = GX_DB_BindParmShort( HStmt_R04609,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R04609,2,GX_CS_LONG,GX_SQL_INTEGER,6,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDate( HStmt_R04609,3,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04608_01
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04608,1,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,4,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04607_01
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04607,1,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,4,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04607,2,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,4,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04606_01
   Gx_err = GX_DB_BindParmShort( HStmt_R04606,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04606,2,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,2,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R04606,3,GX_CS_LONG,GX_SQL_INTEGER,6,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04606,4,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,2,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04606,5,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,2,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R04606,6,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R04606,7,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R04606,8,GX_CS_SHORT,GX_SQL_SMALLINT,2,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R04606,9,GX_CS_SHORT,GX_SQL_SMALLINT,2,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04605_01
   Gx_err = GX_DB_BindParmShort( HStmt_R04605,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R04605,2,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04604_01
   Gx_err = GX_DB_BindParmShort( HStmt_R04604,1,GX_CS_SHORT,GX_SQL_SMALLINT,2,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04603_01
   Gx_err = GX_DB_BindParmShort( HStmt_R04603,1,GX_CS_SHORT,GX_SQL_SMALLINT,2,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR04602_01
   Gx_err = GX_DB_BindParmShort( HStmt_R04602,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04602,2,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,2,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R04602,3,GX_CS_LONG,GX_SQL_INTEGER,6,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04602,4,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04602,5,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R04602,6,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R04602,7,GX_CS_LONG,GX_SQL_INTEGER,6,GX_PARAM_INPUT,0,0)
ENDPROC

***********************
PROCEDURE CDCS0
***********************

   IF GXCONNECTED
   ENDIF
RETURN

***********************
PROCEDURE HLCS2
***********************

   PARAMETERS Key_read, Attrinum
   PRIVATE GXLToBD
   GXLToBD = GXToBeDone
   GXToBeDone = ""
   DO CASE
      CASE Key_read <> 7 .AND. Key_read <> 8
         RETURN
      CASE Key_read = 8
         SET TOPIC TO  [RlCltes]
         HELP
      OTHERWISE
         SET TOPIC TO  [RlCltes]
         HELP
   ENDCASE
RETURN
