
***********************
* RlDepoMx
***********************

   PARAMETERS AV12Emprco , AV19Fechas , AV35Usuari , AV13Fchdes , AV14Fchhas , AV16Nrodes , AV17Nrohas , AV26Ctacod , AV51Valore , Gxarchivo
   * Program generated by GeneXus Version 8_0_3-109
   * Description: List. Depos. Mensuales
   *       Xbase: FOXPRO
   *  Index Type: CDX
   *   Interface: WINDOWS
   *             Client/Server related information
   *         API: odbc
   *      Driver: qesqlserver
   *      Server: dagridb
   *   Data Base: Dagri

   #INCLUDE gxdatain.prg
   IF TYPE("GXToReadEvents") = "U"
      PUBLIC GXToReadEvents
   ENDIF
   GXToReadEvents = .T.
   LOCAL GXReadEvObj
   IF TYPE("GXReadEvents") = "U"
      PRIVATE GXReadEvents
      GXReadEvObj = .T.
   ELSE
      GXReadEvObj = GXReadEvents
   ENDIF
   GXReadEvents = .F.
   IF GXReadEvObj
   ENDIF
   PRIVATE gxHDC, GX_XPage, GX_YPage, GXPrn_Flag
   gxHDC = 0
   GX_XPage = 96
   GX_YPage = 96
   GXPrn_Flag = 0
   ON KEY LABEL ENTER
   IF ! GXReadEvObj
      SET SAFETY OFF
      SET BELL OFF
      SET REPROCESS TO 1
      IF SET("DATE") != "BRITISH"
         SET DATE BRITISH
      ENDIF
      SET EXACT ON
      SET CONFIRM ON
      DO GX_YrLmt WITH 19, 40
      IF SET("HOURS") != 24
         SET HOURS TO 24
      ENDIF
      SET READBORDER OFF
      IF SET("POINT") != "."
         SET POINT TO "."
         SET SEPARATOR TO ","
      ENDIF
      DO GX_DSSet
   ENDIF

   PRIVATE Buf_R08132_986TesLin
   Buf_R08132_986TesLin = 0
   PRIVATE Buf_R08132_985TesNroI
   Buf_R08132_985TesNroI = 0
   PRIVATE Buf_R08135_2EmpCod
   Buf_R08135_2EmpCod = 0
   PRIVATE Buf_R08135_124ChqCta
   Buf_R08135_124ChqCta = 0
   PRIVATE Buf_R08135_123ChqTip
   Buf_R08135_123ChqTip = SPACE(1)
   PRIVATE Buf_R08136_2EmpCod
   Buf_R08136_2EmpCod = 0
   PRIVATE Buf_R08136_124ChqCta
   Buf_R08136_124ChqCta = 0
   PRIVATE Buf_R08136_123ChqTip
   Buf_R08136_123ChqTip = SPACE(1)
   PRIVATE Buf_R08138_87BcoDsc
   Buf_R08138_87BcoDsc = SPACE(40)
   PRIVATE Buf_R08138_77BcoCtaNro
   Buf_R08138_77BcoCtaNro = SPACE(12)
   PRIVATE Buf_R08138_76BcoCta
   Buf_R08138_76BcoCta = 0
   PRIVATE Buf_R08138_86BcoCod
   Buf_R08138_86BcoCod = 0
   PRIVATE HStmt_R08138
   HStmt_R08138 = -1
   PRIVATE Buf_R08137_620MCoDsc
   Buf_R08137_620MCoDsc = SPACE(30)
   PRIVATE Buf_R08137_619MCoCod
   Buf_R08137_619MCoCod = 0
   PRIVATE HStmt_R08137
   HStmt_R08137 = -1
   PRIVATE Buf_R08136_131ChqImp
   Buf_R08136_131ChqImp = 0.00
   PRIVATE Buf_R08136_122ChqLin
   Buf_R08136_122ChqLin = 0
   PRIVATE Buf_R08136_121ChqNroI
   Buf_R08136_121ChqNroI = 0
   PRIVATE HStmt_R08136
   HStmt_R08136 = -1
   PRIVATE Buf_R08135_131ChqImp
   Buf_R08135_131ChqImp = 0.00
   PRIVATE Buf_R08135_122ChqLin
   Buf_R08135_122ChqLin = 0
   PRIVATE Buf_R08135_121ChqNroI
   Buf_R08135_121ChqNroI = 0
   PRIVATE HStmt_R08135
   HStmt_R08135 = -1
   PRIVATE Buf_R08134_1005TesESt
   Buf_R08134_1005TesESt = 0
   PRIVATE Buf_R08134_999TesSerDoc
   Buf_R08134_999TesSerDoc = SPACE(1)
   PRIVATE Buf_R08134_2EmpCod
   Buf_R08134_2EmpCod = 0
   PRIVATE Buf_R08134_998TesTipDoc
   Buf_R08134_998TesTipDoc = SPACE(4)
   PRIVATE Buf_R08134_988TesFch
   Buf_R08134_988TesFch = CTOD("  /  /  ")
   PRIVATE Buf_R08134_1001TesNroDoc
   Buf_R08134_1001TesNroDoc = 0
   PRIVATE Buf_R08134_1006TesCtaDep
   Buf_R08134_1006TesCtaDep = 0
   PRIVATE Buf_R08134_986TesLin
   Buf_R08134_986TesLin = 0
   PRIVATE Buf_R08134_985TesNroI
   Buf_R08134_985TesNroI = 0
   PRIVATE Buf_R08134_995TesNroSub
   Buf_R08134_995TesNroSub = 0
   PRIVATE Buf_R08134_994TesNro
   Buf_R08134_994TesNro = 0
   PRIVATE Buf_R08134_989TesMedCod
   Buf_R08134_989TesMedCod = 0
   PRIVATE HStmt_R08134
   HStmt_R08134 = -1
   PRIVATE Buf_R08133_87BcoDsc
   Buf_R08133_87BcoDsc = SPACE(40)
   PRIVATE Buf_R08133_77BcoCtaNro
   Buf_R08133_77BcoCtaNro = SPACE(12)
   PRIVATE Buf_R08133_76BcoCta
   Buf_R08133_76BcoCta = 0
   PRIVATE Buf_R08133_86BcoCod
   Buf_R08133_86BcoCod = 0
   PRIVATE HStmt_R08133
   HStmt_R08133 = -1
   PRIVATE Buf_R08132_1005TesESt
   Buf_R08132_1005TesESt = 0
   PRIVATE Buf_R08132_999TesSerDoc
   Buf_R08132_999TesSerDoc = SPACE(1)
   PRIVATE Buf_R08132_2EmpCod
   Buf_R08132_2EmpCod = 0
   PRIVATE Buf_R08132_998TesTipDoc
   Buf_R08132_998TesTipDoc = SPACE(4)
   PRIVATE Buf_R08132_988TesFch
   Buf_R08132_988TesFch = CTOD("  /  /  ")
   PRIVATE Buf_R08132_1001TesNroDoc
   Buf_R08132_1001TesNroDoc = 0
   PRIVATE Buf_R08132_989TesMedCod
   Buf_R08132_989TesMedCod = 0
   PRIVATE Buf_R08132_1006TesCtaDep
   Buf_R08132_1006TesCtaDep = 0
   PRIVATE HStmt_R08132
   HStmt_R08132 = -1

   PRIVATE UserCancel, GX_newwin, GX_eject, GX_prn_defa, GX_env_def, GX_retp
   UserCancel = .F.
   GX_newwin = "GXDummyWin"
   GX_eject = .T.
   GX_XProp = 1
   gx_prn_defa = ""
   gx_env_def = .f.
   GX_retp = 0
   PRIVATE gx_oldDVal
   gx_oldDVal = CTOD("  /  /  ")

   PRIVATE currSoapErr, currSoapErrmsg
   currSoapErr = 0
   currSoapErrmsg = ""
   PRIVATE GX_pg_started
   GX_pg_started = .F.
   * Variables Definition
   PRIVATE AV12Emprco
   PRIVATE AV19Fechas
   PRIVATE AV35Usuari
   PRIVATE AV13Fchdes
   PRIVATE AV14Fchhas
   PRIVATE AV16Nrodes
   PRIVATE AV17Nrohas
   PRIVATE AV26Ctacod
   PRIVATE AV51Valore
   PRIVATE Gxarchivo
   PRIVATE Gx_out
   Gx_out = 'SCR'
   PRIVATE R3461McoID
   R3461McoID = SPACE(1)
   PRIVATE R1210McoVt
   R1210McoVt = SPACE(1)
   PRIVATE R1209McoCo
   R1209McoCo = SPACE(1)
   PRIVATE R628McoMBc
   R628McoMBc = SPACE(1)
   PRIVATE R627McoFdi
   R627McoFdi = SPACE(1)
   PRIVATE R626McoTit
   R626McoTit = SPACE(1)
   PRIVATE R625McoCta
   R625McoCta = 0
   PRIVATE R624McoCta
   R624McoCta = SPACE(1)
   PRIVATE R621McoBco
   R621McoBco = SPACE(1)
   PRIVATE R3038ChqRE
   R3038ChqRE = CTOD("  /  /  ")
   PRIVATE R3037ChqRE
   R3037ChqRE = 0
   PRIVATE R3036ChrRE
   R3036ChrRE = SPACE(2)
   PRIVATE R3035ChqRE
   R3035ChqRE = CTOD("  /  /  ")
   PRIVATE R2806ChqEs
   R2806ChqEs = 0
   PRIVATE R2008chqus
   R2008chqus = SPACE(10)
   PRIVATE R2007chqre
   R2007chqre = 0
   PRIVATE R2006chqfc
   R2006chqfc = CTOT("  /  /  ")
   PRIVATE R1994AuxCo
   R1994AuxCo = 0
   PRIVATE R1816ChqOr
   R1816ChqOr = SPACE(50)
   PRIVATE R1733ChqIm
   R1733ChqIm = 0
   PRIVATE R1663ChqCr
   R1663ChqCr = SPACE(1)
   PRIVATE R1651ChqCP
   R1651ChqCP = SPACE(8)
   PRIVATE R1269ChqFc
   R1269ChqFc = CTOD("  /  /  ")
   PRIVATE R149ChqCot
   R149ChqCot = 0.0000
   PRIVATE R146ChqMon
   R146ChqMon = 0
   PRIVATE R145ChqNoO
   R145ChqNoO = SPACE(1)
   PRIVATE R144ChqBco
   R144ChqBco = 0
   PRIVATE R142ChqBco
   R142ChqBco = 0
   PRIVATE R141ChqFch
   R141ChqFch = CTOD("  /  /  ")
   PRIVATE R139ChqPrv
   R139ChqPrv = 0
   PRIVATE R138ChqPrv
   R138ChqPrv = SPACE(2)
   PRIVATE R137ChqNro
   R137ChqNro = 0
   PRIVATE R136ChqEst
   R136ChqEst = 0
   PRIVATE R134ChqCli
   R134ChqCli = 0
   PRIVATE R133ChqCli
   R133ChqCli = SPACE(2)
   PRIVATE R132ChqFch
   R132ChqFch = CTOD("  /  /  ")
   PRIVATE R130ChqTit
   R130ChqTit = SPACE(40)
   PRIVATE R129ChqNro
   R129ChqNro = SPACE(10)
   PRIVATE R128ChqSuc
   R128ChqSuc = 0
   PRIVATE R126ChqBco
   R126ChqBco = 0
   PRIVATE R125ChqFch
   R125ChqFch = CTOD("  /  /  ")
   PRIVATE R124ChqCta
   R124ChqCta = 0
   PRIVATE R123ChqTip
   R123ChqTip = SPACE(1)
   PRIVATE R2526BcoCt
   R2526BcoCt = SPACE(14)
   PRIVATE R2525BcoCt
   R2525BcoCt = SPACE(8)
   PRIVATE R1478BcoCt
   R1478BcoCt = CTOD("  /  /  ")
   PRIVATE R1458BcoCt
   R1458BcoCt = SPACE(12)
   PRIVATE R233BcoMon
   R233BcoMon = 0
   PRIVATE R81BcoNroU
   R81BcoNroU = 0
   PRIVATE R80BcoAut
   R80BcoAut = SPACE(1)
   PRIVATE R79BcoDir
   R79BcoDir = SPACE(40)
   PRIVATE R78BcoSuc
   R78BcoSuc = 0
   PRIVATE R86BcoCod
   R86BcoCod = 0
   PRIVATE R1284TesNr
   R1284TesNr = SPACE(10)
   PRIVATE R1268TesFc
   R1268TesFc = CTOD("  /  /  ")
   PRIVATE R1010TesCo
   R1010TesCo = 0.0000
   PRIVATE R1007TesMo
   R1007TesMo = 0
   PRIVATE R1003TesEn
   R1003TesEn = 0
   PRIVATE R1002TesEn
   R1002TesEn = SPACE(2)
   PRIVATE R1000TesSu
   R1000TesSu = 0
   PRIVATE R997TesFch
   R997TesFch = CTOD("  /  /  ")
   PRIVATE R996TesImp
   R996TesImp = 0.00
   PRIVATE R993TesBco
   R993TesBco = 0
   PRIVATE R991TesBco
   R991TesBco = 0
   PRIVATE R987TesIoE
   R987TesIoE = SPACE(1)
   PRIVATE R619MCoCod
   R619MCoCod = 0
   PRIVATE R620MCoDsc
   R620MCoDsc = SPACE(30)
   PRIVATE R994TesNro
   R994TesNro = 0
   PRIVATE R995TesNro
   R995TesNro = 0
   PRIVATE R985TesNro
   R985TesNro = 0
   PRIVATE R986TesLin
   R986TesLin = 0
   PRIVATE R1006TesCt
   R1006TesCt = 0
   PRIVATE R121ChqNro
   R121ChqNro = 0
   PRIVATE R122ChqLin
   R122ChqLin = 0
   PRIVATE R131ChqImp
   R131ChqImp = 0.00
   PRIVATE R76BcoCta
   R76BcoCta = 0
   PRIVATE R77BcoCtaN
   R77BcoCtaN = SPACE(12)
   PRIVATE R87BcoDsc
   R87BcoDsc = SPACE(40)
   PRIVATE R999TesSer
   R999TesSer = SPACE(1)
   PRIVATE R1005TesES
   R1005TesES = 0
   PRIVATE R989TesMed
   R989TesMed = 0
   PRIVATE R1001TesNr
   R1001TesNr = 0
   PRIVATE R988TesFch
   R988TesFch = CTOD("  /  /  ")
   PRIVATE R998TesTip
   R998TesTip = SPACE(4)
   PRIVATE R2EmpCod
   R2EmpCod = 0
   PRIVATE Gx_emsg
   Gx_emsg = SPACE(70)
   PRIVATE Gx_err
   Gx_err = 0
   PRIVATE RV53Parval
   RV53Parval = SPACE(140)
   PRIVATE RV52Opcion
   RV52Opcion = SPACE(40)
   PRIVATE RV50Ya
   RV50Ya = 0
   PRIVATE RV49Fchmes
   RV49Fchmes = CTOD("  /  /  ")
   PRIVATE RV48K
   RV48K = 0
   PRIVATE RV47Colmed
   RV47Colmed = 0
   PRIVATE RV46Medios[999]
   DIMENSION RV46Medios[999]
   RV46Medios = 0
   PRIVATE RV45Mesani
   RV45Mesani = SPACE(5)
   PRIVATE Gxline1
   Gxline1 = SPACE(50)
   PRIVATE RV43Mcocod
   RV43Mcocod = 0
   PRIVATE RV42J
   RV42J = 0
   PRIVATE RV41Cuenta[10]
   DIMENSION RV41Cuenta[10]
   RV41Cuenta = 0
   PRIVATE RV40Totale[10,999]
   DIMENSION RV40Totale[10,999]
   RV40Totale = 0.00
   PRIVATE RV39Fchmes
   RV39Fchmes = CTOD("  /  /  ")
   PRIVATE RV38I
   RV38I = 0
   PRIVATE Gxline
   Gxline = SPACE(500)
   PRIVATE RV34Que
   RV34Que = SPACE(1)
   PRIVATE RV32Ctacod
   RV32Ctacod = 0
   PRIVATE RV31Chqlin
   RV31Chqlin = 0
   PRIVATE RV30Chqnro
   RV30Chqnro = 0
   PRIVATE RV29Tesimp
   RV29Tesimp = 0.00
   PRIVATE RV28Ctabco
   RV28Ctabco = SPACE(40)
   PRIVATE RV27Ctanro
   RV27Ctanro = SPACE(12)
   PRIVATE RV25Totgra
   RV25Totgra = 0.00
   PRIVATE RV24Totgra
   RV24Totgra = 0.00
   PRIVATE RV23Motdes
   RV23Motdes = SPACE(30)
   PRIVATE RV22Emprno
   RV22Emprno = SPACE(30)
   PRIVATE RV21Toting
   RV21Toting = 0.00
   PRIVATE RV20Nrohaz
   RV20Nrohaz = 0
   PRIVATE RV18Fchhaz
   RV18Fchhaz = CTOD("  /  /  ")
   PRIVATE RV15Motcod
   RV15Motcod = 0
   PRIVATE RV11Monimp
   RV11Monimp = 0.00
   * Level Flags
   PRIVATE LEVEL3
   LEVEL3 = .F.
   PRIVATE LEVEL2
   LEVEL2 = .F.
   PRIVATE LEVEL4
   LEVEL4 = .F.
   PRIVATE LEVEL7
   LEVEL7 = .F.
   PRIVATE LEVEL8
   LEVEL8 = .F.
   PRIVATE LEVEL6
   LEVEL6 = .F.
   PRIVATE LEVEL5
   LEVEL5 = .F.
   PRIVATE LEVEL9
   LEVEL9 = .F.
   PRIVATE LEVEL10
   LEVEL10 = .F.
   PRIVATE LEVEL1
   LEVEL1 = .F.
   * Cursors Definition
   PRIVATE GX_OP7
   GX_OP7 = .F.
   PRIVATE GX_REC7
   GX_REC7 = 0
   PRIVATE GX_OP9
   GX_OP9 = .F.
   PRIVATE GX_REC9
   GX_REC9 = 0
   PRIVATE GX_OP62
   GX_OP62 = .F.
   PRIVATE GX_REC62
   GX_REC62 = 0
   PRIVATE GX_OP108
   GX_OP108 = .F.
   PRIVATE GX_REC108
   GX_REC108 = 0
   PRIVATE GX_OP14
   GX_OP14 = .F.
   PRIVATE GX_REC14
   GX_REC14 = 0
   * Gx formulas
   Gx_err = 0
   * Device settings
   PRIVATE old_area, rpt_name, RptView
   old_area = 0
   rpt_name = " "
   RptView = .F.
   LEVEL1 = .T.
   IF EMPTY( AV14Fchhas )
      RV18Fchhaz = GXFADDYW( AV19Fechas , 10 )
   ELSE
      RV18Fchhaz = AV14Fchhas
   ENDIF
   AV13Fchdes = GXFEOMVF( GXFADDMW( AV13Fchdes , -1 ) ) + 1
   RV18Fchhaz = GXFEOMVF( RV18Fchhaz )
   IF EMPTY( AV17Nrohas )
      RV20Nrohaz = 99999999
   ELSE
      RV20Nrohaz = AV17Nrohas
   ENDIF
   RV50Ya = 0
   RV46Medios = 0
   RV47Colmed = 0
   LEVEL2 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08132" , @HStmt_R08132 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08132","",GX_CURSOR_TYPE_READONLY,@HStmt_R08132) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT [TesNroI], [TesLin], [TesCtaDep], [TesMedCod], [TesNroDoc], [TesFch], [TesTipDoc], "
      cmdbuf = cmdbuf + "  [EmpCod], [TesSerDoc], [TesESt] FROM [TESCYP] (NOLOCK) WHERE ([EmpCod] = ? and [TesTipDoc] "
      cmdbuf = cmdbuf + "  = 'DEPO' and [TesFch] >= ? and [TesNroDoc] >= ?) AND ([TesCtaDep] = ? or ? = 0) "
      cmdbuf = cmdbuf + "  AND ([TesNroDoc] <= ?) AND ([TesSerDoc] = ? or ? = 'T') AND ([TesFch] <= ?) ORDER "
      cmdbuf = cmdbuf + "  BY [EmpCod], [TesTipDoc], [TesFch], [TesNroDoc]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08132,cmdbuf)
      Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R08132,100)
      GX_DB_BindColsR08132_01 ()
      GX_DB_BindParmR08132_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_R08132,1,@AV12Emprco,0)
   Gx_err = GX_DB_SetDate( HStmt_R08132,2,@AV13Fchdes,0)
   Gx_err = GX_DB_SetLong( HStmt_R08132,3,@AV16Nrodes,0)
   Gx_err = GX_DB_SetInt( HStmt_R08132,4,@AV26Ctacod,0)
   Gx_err = GX_DB_SetInt( HStmt_R08132,5,@AV26Ctacod,0)
   Gx_err = GX_DB_SetLong( HStmt_R08132,6,@RV20Nrohaz,0)
   Gx_err = GX_DB_SetStr( HStmt_R08132,7,AV51Valore,1,0)
   Gx_err = GX_DB_SetStr( HStmt_R08132,8,AV51Valore,1,0)
   Gx_err = GX_DB_SetDate( HStmt_R08132,9,@RV18Fchhaz,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08132) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R08132 = Gx_err
   GX_DB_GetR08132_01 ()
   DO WHILE R08132 <> 101
      BRKML2 = .F.
      R1006TesCt = Buf_R08132_1006TesCtaDep
      R989TesMed = Buf_R08132_989TesMedCod
      R1001TesNr = Buf_R08132_1001TesNroDoc
      R988TesFch = Buf_R08132_988TesFch
      R998TesTip = Buf_R08132_998TesTipDoc
      R2EmpCod = Buf_R08132_2EmpCod
      R999TesSer = Buf_R08132_999TesSerDoc
      R1005TesES = Buf_R08132_1005TesESt
      IF R1005TesES = 2
         LEVEL3 = .T.
         DO WHILE R08132 <> 101 .AND. Buf_R08132_2EmpCod=R2EmpCod .AND. Buf_R08132_998TesTipDoc=R998TesTip .AND. Buf_R08132_988TesFch=R988TesFch .AND. Buf_R08132_1001TesNroDoc=R1001TesNr
            BRKML2 = .F.
            R1006TesCt = Buf_R08132_1006TesCtaDep
            R989TesMed = Buf_R08132_989TesMedCod
            IF R1006TesCt = AV26Ctacod .OR. AV26Ctacod = 0
               IF RV46Medios[R989TesMed] = 0
                  RV47Colmed = RV47Colmed + 1
                  RV46Medios[R989TesMed] = RV47Colmed
               ENDIF
            ENDIF
            * Check if program is canceled.
            DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
            IF UserCancel
               EXIT
            ENDIF
            BRKML2 = .T.
            Gx_eop = 1
            DO WHILE Gx_eop != 0
               Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R08132) ,  ,  ,  , CS_SQLSRV ,  )
            ENDDO
            R08132 = Gx_err
            GX_DB_GetR08132_01 ()
            IF UserCancel
               EXIT
            ENDIF
         ENDDO
         LEVEL3 = .F.
      ENDIF
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      IF .NOT. BRKML2
         BRKML2 = .T.
         Gx_eop = 1
         DO WHILE Gx_eop != 0
            Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R08132) ,  ,  ,  , CS_SQLSRV ,  )
         ENDDO
         R08132 = Gx_err
         GX_DB_GetR08132_01 ()
      ENDIF
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08132) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL2 = .F.
   DO CASE
      CASE AV51Valore = "V"
         RV52Opcion = "Listado de Depositos de Valores Negociables Mensuales"
      CASE AV51Valore = "T"
         RV52Opcion = "Listado de TODOS los Depositos Mensuales"
      OTHERWISE
         RV52Opcion = "Listado de Depositos (Sin Valores Negociables) Mensuales"
   ENDCASE
   DO RLeeEmp WITH AV12Emprco , RV22Emprno
   LEVEL4 = .T.
   DO GX_CSC01
   IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08133" , @HStmt_R08133 )
      Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08133","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_R08133) ,  ,  ,  , CS_SQLSRV ,  )
      cmdbuf = " SELECT T1.[BcoCod], T1.[BcoCta], T1.[BcoCtaNro], T2.[BcoDsc] FROM ([CTAS] T1 (NOLOCK) "
      cmdbuf = cmdbuf + "  LEFT JOIN [BANCOS] T2 (NOLOCK) ON T2.[BcoCod] = T1.[BcoCod]) WHERE T1.[BcoCta] = "
      cmdbuf = cmdbuf + "  ? ORDER BY T1.[BcoCta]  "
      Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08133,cmdbuf)
      GX_DB_BindColsR08133_01 ()
      GX_DB_BindParmR08133_01 ()
   ENDIF
   Gx_err = GX_DB_SetInt( HStmt_R08133,1,@AV26Ctacod,0)
   Gx_eop = 1
   DO WHILE Gx_eop != 0
      Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08133) ,  ,  ,  , CS_SQLSRV ,  )
   ENDDO
   R08133 = Gx_err
   GX_DB_GetR08133_01 ()
   DO WHILE R08133 <> 101
      R86BcoCod = Buf_R08133_86BcoCod
      R76BcoCta = Buf_R08133_76BcoCta
      R77BcoCtaN = Buf_R08133_77BcoCtaNro
      R87BcoDsc = Buf_R08133_87BcoDsc
      R87BcoDsc = Buf_R08133_87BcoDsc
      RV27Ctanro = R77BcoCtaN
      RV28Ctabco = R87BcoDsc
      * Check if program is canceled.
      DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
      IF UserCancel
         EXIT
      ENDIF
      * Exiting from a For First loop.
      EXIT
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08133) ,  ,  ,  , CS_SQLSRV ,  )
   LEVEL4 = .F.
   DO RParam WITH AV12Emprco , "TEMP" , "CARPETA" , RV53Parval
   Gxarchivo = ALLTRIM( RV53Parval ) + "DeposMen" + ALLTRIM( str( hour( GXSvr("Now" ) ) , 2 ) ) + ALLTRIM( str( minute( GXSvr("Now" ) ) , 2 ) ) + ALLTRIM( str( SEC( GXSvr("Now" ) ) , 2 ) ) + ".xls"
   * User Code
   gxArch = fcreate( gxArchivo )
   Gxline = "<TABLE cellSpacing='0' cellPadding='0' border='1'><b><TR><TD colSpan='23'><STRONG>" + RV52Opcion + "</STRONG></TD></TR>"
   * User Code
   fputs(gxArch, gxline)
   IF AV26Ctacod <> 0
      Gxline = "<tr><td><STRONG>" + "Cuenta" + "</STRONG></td><td><STRONG>" + str( AV26Ctacod , 3 ) + "</STRONG></td><td><STRONG>" + RV27Ctanro + "</STRONG></td><td><STRONG>" + RV28Ctabco + "</STRONG></td></tr>"
      * User Code
      fputs(gxArch,gxline)
   ENDIF
   RV49Fchmes = AV13Fchdes
   RV39Fchmes = GXFEOMVF( AV13Fchdes )
   DO WHILE RV39Fchmes <= RV18Fchhaz
      RV40Totale = 0
      RV41Cuenta = 0
      LEVEL5 = .T.
      DO GX_CSC01
      IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08134" , @HStmt_R08134 )
         Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08134","",GX_CURSOR_TYPE_READONLY,@HStmt_R08134) ,  ,  ,  , CS_SQLSRV ,  )
         cmdbuf = " SELECT [TesMedCod], [TesNro], [TesNroSub], [TesNroI], [TesLin], [TesCtaDep], [TesNroDoc], "
         cmdbuf = cmdbuf + "  [TesFch], [TesTipDoc], [EmpCod], [TesSerDoc], [TesESt] FROM [TESCYP] (NOLOCK) WHERE "
         cmdbuf = cmdbuf + "  ([EmpCod] = ? and [TesTipDoc] = 'DEPO' and [TesFch] >= ? and [TesNroDoc] >= ?) AND "
         cmdbuf = cmdbuf + "  ([TesCtaDep] = ? or ? = 0) AND ([TesNroDoc] <= ?) AND ([TesSerDoc] = ? or ? = 'T') "
         cmdbuf = cmdbuf + "  AND ([TesFch] <= ?) ORDER BY [EmpCod], [TesTipDoc], [TesFch], [TesNroDoc]  "
         Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08134,cmdbuf)
         Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R08134,100)
         GX_DB_BindColsR08134_01 ()
         GX_DB_BindParmR08134_01 ()
      ENDIF
      Gx_err = GX_DB_SetInt( HStmt_R08134,1,@AV12Emprco,0)
      Gx_err = GX_DB_SetDate( HStmt_R08134,2,@RV49Fchmes,0)
      Gx_err = GX_DB_SetLong( HStmt_R08134,3,@AV16Nrodes,0)
      Gx_err = GX_DB_SetInt( HStmt_R08134,4,@AV26Ctacod,0)
      Gx_err = GX_DB_SetInt( HStmt_R08134,5,@AV26Ctacod,0)
      Gx_err = GX_DB_SetLong( HStmt_R08134,6,@RV20Nrohaz,0)
      Gx_err = GX_DB_SetStr( HStmt_R08134,7,AV51Valore,1,0)
      Gx_err = GX_DB_SetStr( HStmt_R08134,8,AV51Valore,1,0)
      Gx_err = GX_DB_SetDate( HStmt_R08134,9,@RV39Fchmes,0)
      Gx_eop = 1
      DO WHILE Gx_eop != 0
         Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08134) ,  ,  ,  , CS_SQLSRV ,  )
      ENDDO
      R08134 = Gx_err
      GX_DB_GetR08134_01 ()
      DO WHILE R08134 <> 101
         BRKML5 = .F.
         R989TesMed = Buf_R08134_989TesMedCod
         R994TesNro = Buf_R08134_994TesNro
         R995TesNro = Buf_R08134_995TesNroSub
         R985TesNro = Buf_R08134_985TesNroI
         R986TesLin = Buf_R08134_986TesLin
         R1006TesCt = Buf_R08134_1006TesCtaDep
         R1001TesNr = Buf_R08134_1001TesNroDoc
         R988TesFch = Buf_R08134_988TesFch
         R998TesTip = Buf_R08134_998TesTipDoc
         R2EmpCod = Buf_R08134_2EmpCod
         R999TesSer = Buf_R08134_999TesSerDoc
         R1005TesES = Buf_R08134_1005TesESt
         IF R1005TesES = 2
            RV38I = 1
            DO WHILE RV38I <= 10
               IF RV41Cuenta[RV38I] = 0
                  RV41Cuenta[RV38I] = R1006TesCt
                  EXIT
               ELSE
                  IF RV41Cuenta[RV38I] = R1006TesCt
                     EXIT
                  ENDIF
               ENDIF
               RV38I = RV38I + 1
               IF UserCancel
                  EXIT
               ENDIF
            ENDDO
            IF RV38I <= 10
               LEVEL6 = .T.
               DO WHILE R08134 <> 101 .AND. Buf_R08134_2EmpCod=R2EmpCod .AND. Buf_R08134_998TesTipDoc=R998TesTip .AND. Buf_R08134_988TesFch=R988TesFch .AND. Buf_R08134_1001TesNroDoc=R1001TesNr
                  BRKML5 = .F.
                  R989TesMed = Buf_R08134_989TesMedCod
                  R994TesNro = Buf_R08134_994TesNro
                  R995TesNro = Buf_R08134_995TesNroSub
                  R985TesNro = Buf_R08134_985TesNroI
                  R986TesLin = Buf_R08134_986TesLin
                  R1006TesCt = Buf_R08134_1006TesCtaDep
                  IF R1006TesCt = AV26Ctacod .OR. AV26Ctacod = 0
                     IF R989TesMed = 3
                        RV30Chqnro = R994TesNro
                        RV31Chqlin = R995TesNro
                        LEVEL7 = .T.
                        DO GX_CSC01
                        IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08135" , @HStmt_R08135 )
                           Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08135","",GX_CURSOR_TYPE_READONLY_NOTNESTED,@HStmt_R08135) ,  ,  ,  , CS_SQLSRV ,  )
                           cmdbuf = " SELECT [ChqTip], [ChqCta], [EmpCod], [ChqNroI], [ChqLin], [ChqImp] FROM [CHQS] (NOLOCK) "
                           cmdbuf = cmdbuf + "  WHERE [EmpCod] = ? and [ChqNroI] = ? and [ChqLin] = ? ORDER BY [EmpCod]  "
                           Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08135,cmdbuf)
                           Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R08135,100)
                           GX_DB_BindColsR08135_01 ()
                           GX_DB_BindParmR08135_01 ()
                        ENDIF
                        Gx_err = GX_DB_SetInt( HStmt_R08135,1,@R2EmpCod,0)
                        Gx_err = GX_DB_SetDouble( HStmt_R08135,2,@RV30Chqnro,0)
                        Gx_err = GX_DB_SetInt( HStmt_R08135,3,@RV31Chqlin,0)
                        Gx_eop = 1
                        DO WHILE Gx_eop != 0
                           Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08135) ,  ,  ,  , CS_SQLSRV ,  )
                        ENDDO
                        R08135 = Gx_err
                        GX_DB_GetR08135_01 ()
                        DO WHILE R08135 <> 101
                           R121ChqNro = Buf_R08135_121ChqNroI
                           R122ChqLin = Buf_R08135_122ChqLin
                           R131ChqImp = Buf_R08135_131ChqImp
                           RV29Tesimp = R131ChqImp
                           * Check if program is canceled.
                           DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
                           IF UserCancel
                              EXIT
                           ENDIF
                           Gx_eop = 1
                           DO WHILE Gx_eop != 0
                              Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R08135) ,  ,  ,  , CS_SQLSRV ,  )
                           ENDDO
                           R08135 = Gx_err
                           GX_DB_GetR08135_01 ()
                           IF UserCancel
                              EXIT
                           ENDIF
                        ENDDO
                        Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08135) ,  ,  ,  , CS_SQLSRV ,  )
                        LEVEL7 = .F.
                     ELSE
                        RV30Chqnro = R985TesNro
                        RV31Chqlin = R986TesLin
                        LEVEL8 = .T.
                        DO GX_CSC01
                        IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08136" , @HStmt_R08136 )
                           Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08136","",GX_CURSOR_TYPE_READONLY_NOTNESTED,@HStmt_R08136) ,  ,  ,  , CS_SQLSRV ,  )
                           cmdbuf = " SELECT [ChqTip], [ChqCta], [EmpCod], [ChqNroI], [ChqLin], [ChqImp] FROM [CHQS] (NOLOCK) "
                           cmdbuf = cmdbuf + "  WHERE [EmpCod] = ? and [ChqNroI] = ? and [ChqLin] = ? ORDER BY [EmpCod]  "
                           Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08136,cmdbuf)
                           Gx_err = GX_DB_Set_StmtFetchSize( HStmt_R08136,100)
                           GX_DB_BindColsR08136_01 ()
                           GX_DB_BindParmR08136_01 ()
                        ENDIF
                        Gx_err = GX_DB_SetInt( HStmt_R08136,1,@R2EmpCod,0)
                        Gx_err = GX_DB_SetDouble( HStmt_R08136,2,@RV30Chqnro,0)
                        Gx_err = GX_DB_SetInt( HStmt_R08136,3,@RV31Chqlin,0)
                        Gx_eop = 1
                        DO WHILE Gx_eop != 0
                           Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08136) ,  ,  ,  , CS_SQLSRV ,  )
                        ENDDO
                        R08136 = Gx_err
                        GX_DB_GetR08136_01 ()
                        DO WHILE R08136 <> 101
                           R121ChqNro = Buf_R08136_121ChqNroI
                           R122ChqLin = Buf_R08136_122ChqLin
                           R131ChqImp = Buf_R08136_131ChqImp
                           RV29Tesimp = R131ChqImp
                           * Check if program is canceled.
                           DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
                           IF UserCancel
                              EXIT
                           ENDIF
                           Gx_eop = 1
                           DO WHILE Gx_eop != 0
                              Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R08136) ,  ,  ,  , CS_SQLSRV ,  )
                           ENDDO
                           R08136 = Gx_err
                           GX_DB_GetR08136_01 ()
                           IF UserCancel
                              EXIT
                           ENDIF
                        ENDDO
                        Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08136) ,  ,  ,  , CS_SQLSRV ,  )
                        LEVEL8 = .F.
                     ENDIF
                     RV41Cuenta[RV38I] = R1006TesCt
                     IF RV46Medios[R989TesMed] = 0
                        RV47Colmed = RV47Colmed + 1
                        RV46Medios[R989TesMed] = RV47Colmed
                     ENDIF
                     RV40Totale[RV38I,R989TesMed] = RV40Totale[RV38I,R989TesMed] + RV29Tesimp
                  ENDIF
                  * Check if program is canceled.
                  DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
                  IF UserCancel
                     EXIT
                  ENDIF
                  BRKML5 = .T.
                  Gx_eop = 1
                  DO WHILE Gx_eop != 0
                     Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R08134) ,  ,  ,  , CS_SQLSRV ,  )
                  ENDDO
                  R08134 = Gx_err
                  GX_DB_GetR08134_01 ()
                  IF UserCancel
                     EXIT
                  ENDIF
               ENDDO
               LEVEL6 = .F.
            ENDIF
         ENDIF
         * Check if program is canceled.
         DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
         IF UserCancel
            EXIT
         ENDIF
         IF .NOT. BRKML5
            BRKML5 = .T.
            Gx_eop = 1
            DO WHILE Gx_eop != 0
               Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchNext( HStmt_R08134) ,  ,  ,  , CS_SQLSRV ,  )
            ENDDO
            R08134 = Gx_err
            GX_DB_GetR08134_01 ()
         ENDIF
         IF UserCancel
            EXIT
         ENDIF
      ENDDO
      Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08134) ,  ,  ,  , CS_SQLSRV ,  )
      LEVEL5 = .F.
      RV38I = 1
      DO WHILE RV38I <= 10
         IF RV41Cuenta[RV38I] <> 0
            IF RV50Ya = 0
               RV50Ya = 1
               Gxline = "<tr><td>" + "Mes/Año" + "</td><td>" + "Cuenta " + "</td><td>" + "Banco" + "</td>"
               RV42J = 1
               DO WHILE RV42J <= 999
                  IF RV46Medios[RV42J] <> 0
                     RV43Mcocod = RV42J
                     LEVEL9 = .T.
                     DO GX_CSC01
                     IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08137" , @HStmt_R08137 )
                        Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08137","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_R08137) ,  ,  ,  , CS_SQLSRV ,  )
                        cmdbuf = " SELECT [MCoCod], [MCoDsc] FROM [MEDCOB] (NOLOCK) WHERE [MCoCod] = ? ORDER BY [MCoCod] "
                        cmdbuf = cmdbuf + "   "
                        Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08137,cmdbuf)
                        GX_DB_BindColsR08137_01 ()
                        GX_DB_BindParmR08137_01 ()
                     ENDIF
                     Gx_err = GX_DB_SetInt( HStmt_R08137,1,@RV43Mcocod,0)
                     Gx_eop = 1
                     DO WHILE Gx_eop != 0
                        Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08137) ,  ,  ,  , CS_SQLSRV ,  )
                     ENDDO
                     R08137 = Gx_err
                     GX_DB_GetR08137_01 ()
                     DO WHILE R08137 <> 101
                        R619MCoCod = Buf_R08137_619MCoCod
                        R620MCoDsc = Buf_R08137_620MCoDsc
                        Gxline = Gxline + "<td>" + R620MCoDsc + "</td>"
                        * Check if program is canceled.
                        DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
                        IF UserCancel
                           EXIT
                        ENDIF
                        * Exiting from a For First loop.
                        EXIT
                        IF UserCancel
                           EXIT
                        ENDIF
                     ENDDO
                     Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08137) ,  ,  ,  , CS_SQLSRV ,  )
                     LEVEL9 = .F.
                  ENDIF
                  RV42J = RV42J + 1
                  IF UserCancel
                     EXIT
                  ENDIF
               ENDDO
               Gxline = Gxline + "</tr>"
               * User Code
               fputs(gxArch, gxline)
            ENDIF
            RV32Ctacod = RV41Cuenta[RV38I]
            LEVEL10 = .T.
            DO GX_CSC01
            IF .NOT. GX_DB_StmtIsDef( HConn_Default , "R08138" , @HStmt_R08138 )
               Gx_Err = Gx_odbc_mrc( GX_DB_Declare_StmtEx( HConn_Default,"RLDEPOMX","R08138","",GX_CURSOR_TYPE_READONLY_FORFIRST,@HStmt_R08138) ,  ,  ,  , CS_SQLSRV ,  )
               cmdbuf = " SELECT T1.[BcoCod], T1.[BcoCta], T1.[BcoCtaNro], T2.[BcoDsc] FROM ([CTAS] T1 (NOLOCK) "
               cmdbuf = cmdbuf + "  LEFT JOIN [BANCOS] T2 (NOLOCK) ON T2.[BcoCod] = T1.[BcoCod]) WHERE T1.[BcoCta] = "
               cmdbuf = cmdbuf + "  ? ORDER BY T1.[BcoCta]  "
               Gx_err = GX_DB_Set_StmtCmdText( HStmt_R08138,cmdbuf)
               GX_DB_BindColsR08138_01 ()
               GX_DB_BindParmR08138_01 ()
            ENDIF
            Gx_err = GX_DB_SetInt( HStmt_R08138,1,@RV32Ctacod,0)
            Gx_eop = 1
            DO WHILE Gx_eop != 0
               Gx_Err = Gx_odbc_mrc( GX_DB_StmtFetchFirst( HStmt_R08138) ,  ,  ,  , CS_SQLSRV ,  )
            ENDDO
            R08138 = Gx_err
            GX_DB_GetR08138_01 ()
            DO WHILE R08138 <> 101
               R86BcoCod = Buf_R08138_86BcoCod
               R76BcoCta = Buf_R08138_76BcoCta
               R77BcoCtaN = Buf_R08138_77BcoCtaNro
               R87BcoDsc = Buf_R08138_87BcoDsc
               R87BcoDsc = Buf_R08138_87BcoDsc
               RV27Ctanro = R77BcoCtaN
               RV28Ctabco = R87BcoDsc
               * Check if program is canceled.
               DO GX_RPTCW WITH "Cancela el programa (S/N)?" , "Programa cancelado por el usuario" , UserCancel
               IF UserCancel
                  EXIT
               ENDIF
               * Exiting from a For First loop.
               EXIT
               IF UserCancel
                  EXIT
               ENDIF
            ENDDO
            Gx_Err = Gx_odbc_mrc( GX_DB_SetClosable( HStmt_R08138) ,  ,  ,  , CS_SQLSRV ,  )
            LEVEL10 = .F.
            RV45Mesani = str( month( RV39Fchmes ) , 2 ) + "/" + str( year( RV39Fchmes ) , 4 )
            Gxline = "<tr><td>" + RV45Mesani + "</td><td>" + RV27Ctanro + "</td><td>" + RV28Ctabco + "</td><td>"
            RV48K = 1
            RV42J = 1
            DO WHILE RV42J <= 999
               IF RV40Totale[RV38I,RV42J] <> 0
                  DO WHILE RV48K < RV42J
                     IF RV46Medios[RV48K] <> 0
                        Gxline = Gxline + "</td><td>"
                     ENDIF
                     RV48K = RV48K + 1
                     IF UserCancel
                        EXIT
                     ENDIF
                  ENDDO
                  Gxline = Gxline + str( RV40Totale[RV38I,RV42J] , 10 , 2 ) + "</td><td>"
                  RV48K = RV48K + 1
               ENDIF
               RV42J = RV42J + 1
               IF UserCancel
                  EXIT
               ENDIF
            ENDDO
            Gxline = Gxline + "</tr>"
            * User Code
            fputs(gxArch, gxline)
         ENDIF
         RV38I = RV38I + 1
         IF UserCancel
            EXIT
         ENDIF
      ENDDO
      RV49Fchmes = GXFADDMW( RV49Fchmes , 1 )
      RV39Fchmes = GXFEOMVF( RV49Fchmes )
      IF UserCancel
         EXIT
      ENDIF
   ENDDO
   * User Code
   fclose(gxArch)
   RV38I = opendocument( Gxarchivo )
   DO EPML0
   DO ReleaseReport IN GXForm.prg
   RETURN
   GX_retp = 0
* End Program

***********************
PROCEDURE EPML0
***********************

   DO CDML0
   IF WEXIST( GX_newwin )
      RELEASE WINDOW (GX_newwin)
      IF !EMPTY( LastWin )
         ACTIVATE WINDOW (LastWin)
         MODIFY WINDOW (LastWin) CLOSE
      ENDIF
   ENDIF
RETURN
PROCEDURE GX_DB_GetR08138_01
   Gx_err = GX_DB_GetColInt( HStmt_R08138,1,@Buf_R08138_86BcoCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08138,2,@Buf_R08138_76BcoCta,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08138,3,@Buf_R08138_77BcoCtaNro,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08138,4,@Buf_R08138_87BcoDsc,0)
ENDPROC

PROCEDURE GX_DB_GetR08137_01
   Gx_err = GX_DB_GetColInt( HStmt_R08137,1,@Buf_R08137_619MCoCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08137,2,@Buf_R08137_620MCoDsc,0)
ENDPROC

PROCEDURE GX_DB_GetR08136_01
   Gx_err = GX_DB_GetColStr( HStmt_R08136,1,@Buf_R08136_123ChqTip,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08136,2,@Buf_R08136_124ChqCta,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08136,3,@Buf_R08136_2EmpCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R08136,4,@Buf_R08136_121ChqNroI,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08136,5,@Buf_R08136_122ChqLin,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R08136,6,@Buf_R08136_131ChqImp,0)
ENDPROC

PROCEDURE GX_DB_GetR08135_01
   Gx_err = GX_DB_GetColStr( HStmt_R08135,1,@Buf_R08135_123ChqTip,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08135,2,@Buf_R08135_124ChqCta,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08135,3,@Buf_R08135_2EmpCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R08135,4,@Buf_R08135_121ChqNroI,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08135,5,@Buf_R08135_122ChqLin,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R08135,6,@Buf_R08135_131ChqImp,0)
ENDPROC

PROCEDURE GX_DB_GetR08134_01
   Gx_err = GX_DB_GetColInt( HStmt_R08134,1,@Buf_R08134_989TesMedCod,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R08134,2,@Buf_R08134_994TesNro,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08134,3,@Buf_R08134_995TesNroSub,0)
   Gx_err = GX_DB_GetColDouble( HStmt_R08134,4,@Buf_R08134_985TesNroI,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08134,5,@Buf_R08134_986TesLin,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08134,6,@Buf_R08134_1006TesCtaDep,0)
   Gx_err = GX_DB_GetColLong( HStmt_R08134,7,@Buf_R08134_1001TesNroDoc,0)
   Gx_err = GX_DB_GetColDate( HStmt_R08134,8,@Buf_R08134_988TesFch,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08134,9,@Buf_R08134_998TesTipDoc,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08134,10,@Buf_R08134_2EmpCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08134,11,@Buf_R08134_999TesSerDoc,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08134,12,@Buf_R08134_1005TesESt,0)
ENDPROC

PROCEDURE GX_DB_GetR08133_01
   Gx_err = GX_DB_GetColInt( HStmt_R08133,1,@Buf_R08133_86BcoCod,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08133,2,@Buf_R08133_76BcoCta,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08133,3,@Buf_R08133_77BcoCtaNro,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08133,4,@Buf_R08133_87BcoDsc,0)
ENDPROC

PROCEDURE GX_DB_GetR08132_01
   Gx_err = GX_DB_GetColDouble( HStmt_R08132,1,@Buf_R08132_985TesNroI,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08132,2,@Buf_R08132_986TesLin,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08132,3,@Buf_R08132_1006TesCtaDep,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08132,4,@Buf_R08132_989TesMedCod,0)
   Gx_err = GX_DB_GetColLong( HStmt_R08132,5,@Buf_R08132_1001TesNroDoc,0)
   Gx_err = GX_DB_GetColDate( HStmt_R08132,6,@Buf_R08132_988TesFch,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08132,7,@Buf_R08132_998TesTipDoc,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08132,8,@Buf_R08132_2EmpCod,0)
   Gx_err = GX_DB_GetColStr( HStmt_R08132,9,@Buf_R08132_999TesSerDoc,0)
   Gx_err = GX_DB_GetColInt( HStmt_R08132,10,@Buf_R08132_1005TesESt,0)
ENDPROC

PROCEDURE GX_DB_BindColsR08138_01
   Gx_err = GX_DB_BindColShort( HStmt_R08138,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08138,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08138,3,0,12,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08138,4,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindColsR08137_01
   Gx_err = GX_DB_BindColShort( HStmt_R08137,1,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08137,2,0,30,0)
ENDPROC
PROCEDURE GX_DB_BindColsR08136_01
   Gx_err = GX_DB_BindColCharEx( HStmt_R08136,1,0,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08136,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08136,3,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R08136,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08136,5,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R08136,6,0)
ENDPROC
PROCEDURE GX_DB_BindColsR08135_01
   Gx_err = GX_DB_BindColCharEx( HStmt_R08135,1,0,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08135,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08135,3,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R08135,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08135,5,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R08135,6,0)
ENDPROC
PROCEDURE GX_DB_BindColsR08134_01
   Gx_err = GX_DB_BindColShort( HStmt_R08134,1,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R08134,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08134,3,0)
   Gx_err = GX_DB_BindColDouble( HStmt_R08134,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08134,5,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08134,6,0)
   Gx_err = GX_DB_BindColLong( HStmt_R08134,7,0)
   Gx_err = GX_DB_BindColDate( HStmt_R08134,8,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08134,9,0,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08134,10,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08134,11,0,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08134,12,0)
ENDPROC
PROCEDURE GX_DB_BindColsR08133_01
   Gx_err = GX_DB_BindColShort( HStmt_R08133,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08133,2,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08133,3,0,12,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08133,4,0,40,0)
ENDPROC
PROCEDURE GX_DB_BindColsR08132_01
   Gx_err = GX_DB_BindColDouble( HStmt_R08132,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08132,2,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08132,3,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08132,4,0)
   Gx_err = GX_DB_BindColLong( HStmt_R08132,5,0)
   Gx_err = GX_DB_BindColDate( HStmt_R08132,6,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08132,7,0,4,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08132,8,0)
   Gx_err = GX_DB_BindColCharEx( HStmt_R08132,9,0,1,0)
   Gx_err = GX_DB_BindColShort( HStmt_R08132,10,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08138_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08138,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08137_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08137,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08136_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08136,1,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_R08136,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R08136,3,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08135_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08135,1,GX_CS_SHORT,GX_SQL_SMALLINT,4,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDouble( HStmt_R08135,2,GX_CS_DOUBLE,GX_SQL_DECIMAL,12,0,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R08135,3,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08134_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08134,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDate( HStmt_R08134,2,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R08134,3,GX_CS_LONG,GX_SQL_INTEGER,8,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R08134,4,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R08134,5,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R08134,6,GX_CS_LONG,GX_SQL_INTEGER,8,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R08134,7,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R08134,8,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmDate( HStmt_R08134,9,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08133_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08133,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
ENDPROC
PROCEDURE GX_DB_BindParmR08132_01
   Gx_err = GX_DB_BindParmShort( HStmt_R08132,1,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmDate( HStmt_R08132,2,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R08132,3,GX_CS_LONG,GX_SQL_INTEGER,8,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R08132,4,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmShort( HStmt_R08132,5,GX_CS_SHORT,GX_SQL_SMALLINT,3,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmLong( HStmt_R08132,6,GX_CS_LONG,GX_SQL_INTEGER,8,GX_PARAM_INPUT,0,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R08132,7,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmCharEx( HStmt_R08132,8,GX_CS_STRING,GX_SQL_CHAR,GX_PARAM_INPUT,0,1,0)
   Gx_err = GX_DB_BindParmDate( HStmt_R08132,9,GX_CS_DATETIME,GX_SQL_TIMESTAMP,GX_PARAM_INPUT,0,0)
ENDPROC

***********************
PROCEDURE CDML0
***********************

   IF GXCONNECTED
   ENDIF
RETURN

***********************
PROCEDURE HLML2
***********************

   PARAMETERS Key_read, Attrinum
   PRIVATE GXLToBD
   GXLToBD = GXToBeDone
   GXToBeDone = ""
   DO CASE
      CASE Key_read <> 7 .AND. Key_read <> 8
         RETURN
      CASE Key_read = 8
         SET TOPIC TO  [RlDepoMx]
         HELP
      OTHERWISE
         SET TOPIC TO  [RlDepoMx]
         HELP
   ENDCASE
RETURN
